### ISSUE TITLE
Large data replications to zenodo give us 413 error

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1284]
This is an issue at Zenodo.  The response code they give us is `413` which means they don't accept that large of a payload.

An example of this is below where the dataset and the single giant file is 64 GB.  It may only fail for individual files that are this large.  I know we've gotten some larger things into Zenodo in the past.

```
result = Stash::ZenodoReplicate::Copier.test_submit(resource_id: 114501)
#<Thread:0x000055e0fb9ad5f8@/apps/dryad/apps/ui/releases/20210512000703/stash/stash_engine/lib/stash/zenodo_software/streamer.rb:48 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        1: from /apps/dryad/apps/ui/releases/20210512000703/stash/stash_engine/lib/stash/zenodo_software/streamer.rb:53:in `block in stream'
/apps/dryad/apps/ui/releases/20210512000703/stash/stash_engine/lib/stash/zenodo_replicate/zenodo_connection.rb:54:in `standard_request': Zenodo response: 413 (Stash::ZenodoReplicate::ZenodoError)
```

**Comment by sfisher** [comment]
I believe this is fixed and haven't seen this exact error in a while or we will encounter it if we do investigation of all the difficulties around large submissions.
