### ISSUE TITLE
Merritt returns a 406 to some async download requests, fix our code if needed

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#197]
A crawler hit urls and produced errors like below.  We can look at if Dash is handing something it's doing right.  I think this may not be urgent and normal user interactions work.

```
A StashEngine::MerrittResponseError occurred in downloads#async_request:

  Merritt async download request: unexpected status 406 for resource ID 102, URL https://merritt.cdlib.org/asyncd/ark%3A%2Fb7280%2Fd1159r/6?user_agent_email=&userFriendly=true&losFrom=uc3%40ucop.edu&losSubject=Your+download+for+Special+Survey+of+Orange+County+2001+is+ready&losBody=The+dataset+that+you+have+requested+is+ready+for+you+to+download.++Please+follow+the+link%0Abelow+to+download+your+file%3A%0A%0A++%3C%25%3D+%40dl_url+%25%3E%0A%0APlease+note+that+this+link+will+expire+in+7+days+from+the+date+of+this+email.++The+content+is+stored%0Aas+a+compressed+file+in+the+%22tar.gz%22+format.++For+many+operating+systems%2C+you+can+extract+the%0Afiles+by+double-clicking+this+archive.++For+Windows+or+other+systems+you+might+require+a+utility%0Asuch+as+7-zip+%28+see+http%3A%2F%2Fwww.7-zip.org%2F+%29+to+extract+the+files.
  /apps/dash2/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/downloads_controller.rb:229:in `raise_merritt_error'


-------------------------------
Request:
-------------------------------

  * URL        : http://dash.ucop.edu/stash/downloads/async_request/102
  * HTTP Method: GET
  * IP address : 64.150.183.176
  * Parameters : {"controller"=>"stash_engine/downloads", "action"=>"async_request", "resource_id"=>"102"}
  * Timestamp  : 2019-02-06 02:28:46 UTC
  * Server : uc3-dash2-prd
  * Rails root : /apps/dash2/apps/ui/releases/20190202000913
  * Process: 30124

-------------------------------
Session:
-------------------------------

  * session id: "460cbfd4cae20c993dd795c3eff2a636"
  * data: {"session_id"=>"460cbfd4cae20c993dd795c3eff2a636",
   "_csrf_token"=>"wVkUe/A3LtpG1yYv5fwiYmHbLwPoVBORGaMw7Z/V0qQ=",
   "search"=>{"id"=>nil}}

-------------------------------
Environment:
-------------------------------

  * HTTP_ACCEPT                                    : */*
  * HTTP_CACHE_CONTROL                             : max-age=259200
  * HTTP_COOKIE                                    : NSC_xxx-vdpq-fev=ffffffff8338570745525d5f4f58455e445a4a423660; _dash2_session=M3ZxWlZoZkhnMUpwNHVxVXV6S0FZY2lpNlZPdHQ3NmlWdDZiRnczRnlnU1Y2ZGR1TExISzZRSEQyN3BRM2hhNkJxZGU1NEJhcWFKM2hESUw3bUU2dklYN3RBdUJPckFBU2xEa3V1NmVsa1FWRDJXMk9qNVczTjVqUlBEcGhEZm9MczBVdVI5cFJaWWUvY2o3dStZSHN1TXdwUWJLTTRVS3k1S3Q0eFpuOUZ3am8wUjhXQ21tNzF3VHg4YnhQUXYvLS0xbXZyK1VUcVZGc0tKTzRXeDhDdnNBPT0%3D--1d52cda7381c6e2aec14df25126a2eb4fe42abbc
  * HTTP_HOST                                      : uc3-dash2-prd.cdlib.org:3000
  * HTTP_REFERER                                   : https://dash.ucop.edu/stash/dataset/doi:10.7280/D1159R
  * HTTP_USER_AGENT                                : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
  * HTTP_VERSION                                   : HTTP/1.1
  * HTTP_VIA                                       : 1.0 s1.bluechipbacklinks.com (squid/3.1.23)
  * HTTP_X_FORWARDED_FOR                           : 69.64.95.89, 64.150.183.176
  * HTTP_X_FORWARDED_HOST                          : dash.ucop.edu
  * HTTP_X_FORWARDED_SERVER                        : dash.ucop.edu
  * ORIGINAL_FULLPATH                              : /stash/downloads/async_request/102
  * ORIGINAL_SCRIPT_NAME                           :
  * PASSENGER_CONNECT_PASSWORD                     : [FILTERED]
  * PATH_INFO                                      : /downloads/async_request/102
  * QUERY_STRING                                   :
  * REMOTE_ADDR                                    : 172.30.32.144
  * REMOTE_PORT                                    : 38698
  * REQUEST_METHOD                                 : GET
  * REQUEST_URI                                    : /stash/downloads/async_request/102
  * ROUTES_47081163366240_SCRIPT_NAME              : /stash
  * ROUTES_47081163546280_SCRIPT_NAME              :
  * SCRIPT_NAME                                    : /stash
  * SERVER_NAME                                    : uc3-dash2-prd.cdlib.org
  * SERVER_PORT                                    : 3000
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : nginx/1.12.2 Phusion_Passenger/5.1.12
  * action_controller.instance                     : #<StashEngine::DownloadsController:0x007f69b97097c8>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x0055a3dd9595d0>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x007f69b96ff020>
  * action_dispatch.cookies_digest                 :
  * action_dispatch.cookies_serializer             : json
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x0055a3e1cb84c0>
  * action_dispatch.logger                         : #<ActiveSupport::Logger:0x0055a3e003ad20>
  * action_dispatch.parameter_filter               : [:password, /^((?-mix:client_secret|code|authentication_token|access_token|refresh_token))$/]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 64.150.183.176
  * action_dispatch.request.accepts                : [#<Mime::Type:0x007f69b96ffcf0 @synonyms=[], @symbol=nil, @string="*/*", @hash=1359976741294767320>]
  * action_dispatch.request.content_type           :
  * action_dispatch.request.formats                : [#<Mime::Type:0x007f69b96ffcf0 @synonyms=[], @symbol=nil, @string="*/*", @hash=1359976741294767320>]
  * action_dispatch.request.parameters             : {"controller"=>"stash_engine/downloads", "action"=>"async_request", "resource_id"=>"102"}
  * action_dispatch.request.path_parameters        : {:controller=>"stash_engine/downloads", :action=>"async_request", :resource_id=>"102"}
  * action_dispatch.request.query_parameters       : {}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"460cbfd4cae20c993dd795c3eff2a636", "_csrf_token"=>"wVkUe/A3LtpG1yYv5fwiYmHbLwPoVBORGaMw7Z/V0qQ=", "search"=>{"id"=>nil}}
  * action_dispatch.request_id                     : 545b3111-432b-4b91-a529-cedcbf78034a
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x0055a3e0093ec0>
  * action_dispatch.secret_key_base                : a920845587556ebc6d3ca4ba76dd6098c0c96d9cd3043f1289112a3d9086f59466ac06702221927a343f4b396e660bd6a6f3dfa4d512ab7fd555e810702042d2
  * action_dispatch.secret_token                   :
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : signed cookie
  * rack.errors                                    : #<IO:0x0055a3dcf39898>
  * rack.hijack                                    : #<Proc:0x007f69b973eec8@/apps/dash2/apps/ui/releases/20190202000913/vendor/bundle/ruby/2.4.0/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:84 (lambda)>
  * rack.hijack?                                   : true
  * rack.input                                     : #<PhusionPassenger::Utils::TeeInput:0x007f69b973f148>
  * rack.multiprocess                              : true
  * rack.multithread                               : false
  * rack.request.cookie_hash                       : {"NSC_xxx-vdpq-fev"=>"ffffffff8338570745525d5f4f58455e445a4a423660", "_dash2_session"=>"M3ZxWlZoZkhnMUpwNHVxVXV6S0FZY2lpNlZPdHQ3NmlWdDZiRnczRnlnU1Y2ZGR1TExISzZRSEQyN3BRM2hhNkJxZGU1NEJhcWFKM2hESUw3bUU2dklYN3RBdUJPckFBU2xEa3V1NmVsa1FWRDJXMk9qNVczTjVqUlBEcGhEZm9MczBVdVI5cFJaWWUvY2o3dStZSHN1TXdwUWJLTTRV...
  * rack.request.cookie_string                     : NSC_xxx-vdpq-fev=ffffffff8338570745525d5f4f58455e445a4a423660; _dash2_session=M3ZxWlZoZkhnMUpwNHVxVXV6S0FZY2lpNlZPdHQ3NmlWdDZiRnczRnlnU1Y2ZGR1TExISzZRSEQyN3BRM2hhNkJxZGU1NEJhcWFKM2hESUw3bUU2dklYN3RBdUJPckFBU2xEa3V1NmVsa1FWRDJXMk9qNVczTjVqUlBEcGhEZm9MczBVdVI5cFJaWWUvY2o3dStZSHN1TXdwUWJLTTRVS3k1S3Q0eFpuOUZ3am8wUjhXQ21tNzF3VHg4YnhQUXYvLS0xbXZyK1VUcVZGc0tKTzRXeDhDdnNBPT0%3D--1d52cda7381c6e2aec14df25126a2eb4fe42abbc
  * rack.request.query_hash                        : {}
  * rack.request.query_string                      :
  * rack.run_once                                  : false
  * rack.session                                   : #<ActionDispatch::Request::Session:0x007f69b97328f8>
  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x007f69b9732858>
  * rack.url_scheme                                : http
  * rack.version                                   : [1, 2]
  * warden                                         : Warden::Proxy:70046029812700 @config={:default_scope=>nil, :scope_defaults=>{}, :default_strategies=>{}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x0055a3e1618e08>}

-------------------------------
Backtrace:
-------------------------------

  /apps/dash2/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/downloads_controller.rb:229:in `raise_merritt_error'
  /apps/dash2/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/downloads_controller.rb:188:in `api_async_download'
  /apps/dash2/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/downloads_controller.rb:40:in `block (2 levels) in async_request'
  /apps/dash2/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/downloads_controller.rb:37:in `async_request'
```

**Comment by ryscher** [comment]
This system was converted to long ago...
