### ISSUE TITLE
Sorting by Author and by "Last Modified By" Fail with error in curator interface

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#210]
I think this is part of the curation status changes.  I can look into it if i get some extra time this sprint.

```
Mysql2::Error: Unknown column 'user2.last_name' in 'order clause': SELECT  `stash_engine_resources`.`id` AS t0_r0, `stash_engine_resources`.`user_id` AS t0_r1, `stash_engine_resources`.`current_resource_state_id` AS t0_r2, `stash_engine_resources`.`created_at` AS t0_r3, `stash_engine_resources`.`updated_at` AS t0_r4, `stash_engine_resources`.`has_geolocation` AS t0_r5, `stash_engine_resources`.`download_uri` AS t0_r6, `stash_engine_resources`.`identifier_id` AS t0_r7, `stash_engine_resources`.`update_uri` AS t0_r8, `stash_engine_resources`.`title` AS t0_r9, `stash_engine_resources`.`current_editor_id` AS t0_r10, `stash_engine_resources`.`publication_date` AS t0_r11, `stash_engine_resources`.`accepted_agreement` AS t0_r12, `stash_engine_resources`.`tenant_id` AS t0_r13, `stash_engine_resources`.`skip_datacite_update` AS t0_r14, `stash_engine_resources`.`skip_emails` AS t0_r15, `stash_engine_resources`.`loosen_validation` AS t0_r16, `stash_engine_resources`.`solr_indexed` AS t0_r17, `stash_engine_resources`.`current_curation_activity_id` AS t0_r18, `stash_engine_identifiers`.`id` AS t1_r0, `stash_engine_identifiers`.`identifier` AS t1_r1, `stash_engine_identifiers`.`identifier_type` AS t1_r2, `stash_engine_identifiers`.`storage_size` AS t1_r3, `stash_engine_identifiers`.`created_at` AS t1_r4, `stash_engine_identifiers`.`updated_at` AS t1_r5, `stash_engine_identifiers`.`latest_resource_id` AS t1_r6, `stash_engine_identifiers`.`license_id` AS t1_r7, `stash_engine_identifiers`.`search_words` AS t1_r8, `stash_engine_users`.`id` AS t2_r0, `stash_engine_users`.`first_name` AS t2_r1, `stash_engine_users`.`last_name` AS t2_r2, `stash_engine_users`.`email` AS t2_r3, `stash_engine_users`.`created_at` AS t2_r4, `stash_engine_users`.`updated_at` AS t2_r5, `stash_engine_users`.`tenant_id` AS t2_r6, `stash_engine_users`.`last_login` AS t2_r7, `stash_engine_users`.`role` AS t2_r8, `stash_engine_users`.`orcid` AS t2_r9, `stash_engine_users`.`migration_token` AS t2_r10, `stash_engine_users`.`old_dryad_email` AS t2_r11, `stash_engine_users`.`eperson_id` AS t2_r12, `stash_engine_users`.`validation_tries` AS t2_r13, `stash_engine_resource_states`.`id` AS t3_r0, `stash_engine_resource_states`.`user_id` AS t3_r1, `stash_engine_resource_states`.`resource_state` AS t3_r2, `stash_engine_resource_states`.`created_at` AS t3_r3, `stash_engine_resource_states`.`updated_at` AS t3_r4, `stash_engine_resource_states`.`resource_id` AS t3_r5, `stash_engine_curation_activities`.`id` AS t4_r0, `stash_engine_curation_activities`.`status` AS t4_r1, `stash_engine_curation_activities`.`user_id` AS t4_r2, `stash_engine_curation_activities`.`note` AS t4_r3, `stash_engine_curation_activities`.`keywords` AS t4_r4, `stash_engine_curation_activities`.`created_at` AS t4_r5, `stash_engine_curation_activities`.`updated_at` AS t4_r6, `stash_engine_curation_activities`.`resource_id` AS t4_r7 FROM `stash_engine_resources` INNER JOIN `stash_engine_identifiers` ON `stash_engine_identifiers`.`id` = `stash_engine_resources`.`identifier_id` INNER JOIN `stash_engine_users` ON `stash_engine_users`.`id` = `stash_engine_resources`.`user_id` INNER JOIN `stash_engine_resource_states` ON `stash_engine_resource_states`.`id` = `stash_engine_resources`.`current_resource_state_id` INNER JOIN `stash_engine_curation_activities` ON `stash_engine_curation_activities`.`id` = `stash_engine_resources`.`current_curation_activity_id` WHERE `stash_engine_resources`.`id` IN (1125, 1133, 1134, 1136, 1209, 1138, 1315, 1155, 1156, 1142, 1143, 1144, 1157, 1158, 1147, 1148, 1149, 1150, 1159, 1319, 1164, 1186, 1185, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1205, 1272, 1196, 1197, 1198, 1199, 1201, 1202, 1203, 1204, 1210, 1214, 1215, 1221, 1223, 1225, 1226, 1227, 1228, 1302, 1230, 1231, 1234, 1236, 1237, 1238, 1242, 1303, 1304, 1305, 1306, 1247, 1248, 1249, 1250, 1255, 1256, 1258, 1263, 1264, 1270, 1271, 1279, 1281, 1282, 1283, 1317, 1287, 1288, 1289, 1291, 1298, 1296, 1310, 1312, 1313, 1316, 1318, 1321, 1322, 1323, 1324)  ORDER BY user2.last_name asc, user2.first_name asc LIMIT 10 OFFSET 0
```

```
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/mysql2_adapter.rb:221:in `exec_query'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `cache_sql'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/relation/finder_methods.rb:356:in `find_with_associations'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/relation.rb:639:in `exec_queries'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/relation.rb:515:in `load'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/relation.rb:243:in `to_a'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/relation/delegation.rb:46:in `each'
/apps/dryad/apps/ui/releases/stash/stash_engine/app/views/stash_engine/admin_datasets/_datasets_table.html.erb:30:in `__apps_dryad_apps_ui_releases_stash_stash_engine_app_views_stash_engine_admin_datasets__datasets_table_html_erb___3907420371759236931_46993398479740'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/template.rb:145:in `block in render'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:166:in `instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/template.rb:333:in `instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/template.rb:143:in `render'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:164:in `block in instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:164:in `instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/renderer/partial_renderer.rb:309:in `render'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/renderer/renderer.rb:51:in `render_partial'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/renderer/renderer.rb:25:in `render'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/helpers/rendering_helper.rb:32:in `render'
/apps/dryad/apps/ui/releases/stash/stash_engine/app/views/stash_engine/admin_datasets/index.html.erb:11:in `__apps_dryad_apps_ui_releases_stash_stash_engine_app_views_stash_engine_admin_datasets_index_html_erb___2364372151983894740_46993391517440'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/template.rb:145:in `block in render'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:166:in `instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/template.rb:333:in `instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/template.rb:143:in `render'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:164:in `block in instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:164:in `instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/renderer/template_renderer.rb:14:in `render'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/renderer/renderer.rb:46:in `render_template'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/renderer/renderer.rb:27:in `render'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/rendering.rb:100:in `_render_template'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/rendering.rb:83:in `render_to_body'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/abstract_controller/rendering.rb:25:in `render'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/rendering.rb:16:in `render'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/apps/dryad/local/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/instrumentation.rb:43:in `render'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/wicked_pdf-1.1.0/lib/wicked_pdf/pdf_helper.rb:42:in `render_with_wicked_pdf'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/mime_responds.rb:217:in `respond_to'
/apps/dryad/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb:20:in `index'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/abstract_controller/base.rb:198:in `process_action'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/rendering.rb:10:in `process_action'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:117:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:505:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/abstract_controller/callbacks.rb:19:in `process_action'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/rescue.rb:29:in `process_action'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:164:in `block in instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:164:in `instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/abstract_controller/base.rb:137:in `process'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/rendering.rb:30:in `process'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal.rb:196:in `dispatch'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal.rb:237:in `block in action'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:30:in `each'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:30:in `serve'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:817:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/engine.rb:518:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/railtie.rb:194:in `public_send'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/railtie.rb:194:in `method_missing'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/routing/mapper.rb:51:in `serve'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:30:in `each'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:30:in `serve'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:817:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:190:in `call!'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:168:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:190:in `call!'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:168:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/builder.rb:63:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/etag.rb:24:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/conditionalget.rb:25:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/head.rb:13:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/flash.rb:260:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/session/abstract/id.rb:225:in `context'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/session/abstract/id.rb:220:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/query_cache.rb:36:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/migration.rb:377:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/reloader.rb:73:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/rack/logger.rb:38:in `call_app'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/rack/logger.rb:20:in `block in call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/tagged_logging.rb:26:in `tagged'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/tagged_logging.rb:68:in `tagged'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/rack/logger.rb:20:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/methodoverride.rb:22:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/runtime.rb:18:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/lock.rb:17:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/static.rb:120:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/static.rb:120:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/static.rb:120:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/sendfile.rb:113:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/engine.rb:518:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/application.rb:165:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/passenger-6.0.1/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/passenger-6.0.1/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/passenger-6.0.1/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/passenger-6.0.1/src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/passenger-6.0.1/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by briri** [comment]
Yes. That looks like its due to the query change for the main Admin landing page. 

The old query did have a 'user2' defined:
https://github.com/CDL-Dryad/stash/blob/e31a1326ee373d10ffefbc6f4b211c05b6b8143d/stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb#L119

We likely just need to add it back into the new query, or update 'user2' to `resource.user` or `resource.current_curation_activity.user` or `resource.current_resource_state.user` ... whichever one is applicable
