### ISSUE TITLE
Invalid tar file?

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2425]
IDK if this is easily fixable or if this file is just invalid. We are using Ruby tar libraries and the error seems to be coming out of the tar libraries (double-check):

```
Error updating container_contents for ALL_ALL_dryad.recode.vcf.tar.gz (id: 471, resource_id: 146): "\x80\x00\x00\x00\x00\x00\x00\x03w\xBA2w" is not an octal string
  Error: ArgumentError "\x80\x00\x00\x00\x00\x00\x00\x03w\xBA2w" is not an octal string
  /usr/share/rubygems/rubygems/package/tar_header.rb:129:in `strict_oct'
  /usr/share/rubygems/rubygems/package/tar_header.rb:110:in `from'
  /usr/share/rubygems/rubygems/package/tar_reader.rb:59:in `each'
  /apps/dryad/apps/ui/releases/20230328233827/lib/stash/compressed/tar_gz.rb:41:in `block (2 levels) in file_entries'
  /usr/share/rubygems/rubygems/package/tar_reader.rb:27:in `new'
  /apps/dryad/apps/ui/releases/20230328233827/lib/stash/compressed/tar_gz.rb:40:in `block in file_entries'
  /apps/dryad/apps/ui/releases/20230328233827/lib/stash/compressed/tar_gz.rb:39:in `wrap'
  /apps/dryad/apps/ui/releases/20230328233827/lib/stash/compressed/tar_gz.rb:39:in `file_entries'
  /apps/dryad/apps/ui/releases/20230328233827/lib/tasks/compressed/info.rb:11:in `files'
  /apps/dryad/apps/ui/releases/20230328233827/lib/tasks/compressed.rake:31:in `block (3 levels) in <main>'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/relation/delegation.rb:88:in `each'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/relation/delegation.rb:88:in `each'
  /apps/dryad/apps/ui/releases/20230328233827/lib/tasks/compressed.rake:17:in `each_with_index'
  /apps/dryad/apps/ui/releases/20230328233827/lib/tasks/compressed.rake:17:in `block (2 levels) in <main>'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/command.rb:50:in `invoke'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/commands.rb:18:in `<main>'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
  bin/rails:4:in `<main>'
```

**Comment by sfisher** [comment]
I don't know what to do with this.  The file extracts with Linux tar utilities, but there may be a bug or overly strict extraction in Ruby with `rubygems/package` (which is used for Rubygems).  I also couldn't get any file entries with `minitar` gem (though no error given).

I believe this is caused by https://github.com/rubygems/rubygems/issues/2213 (also referenced from https://github.com/chef-boneyard/chef-dk/issues/1549 and some other places).  The octal code in the header doesn't meet some strict guidelines.  Apparently an older version of rubygems (2.7.5 or earlier) allows this and perhaps was updated for security reasons.

I tried revising my streaming code, updating to the latest rubygems with no success and tested without streaming directly from my file system.  I got the same results so I believe this is really caused by the ruby `rubygems/package` library which reads tar files.

I'm inclined to ignore this and maybe update some items manually since it only happened once in 1,000 files (about half of which were tar.gz files).
