### ISSUE TITLE
EZID now failing to update on dev

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2546]
When trying to publish using EZID in development it now fails.  Has something changed at EZID?

Net::HTTPServerException (403 "Forbidden"):

lib/stash/doi/ezid_gen.rb:54:in `update_metadata'
lib/stash/doi/id_gen.rb:52:in `update_identifier_metadata!'
app/models/stash_engine/curation_activity.rb:187:in `submit_to_datacite'
app/models/stash_engine/curation_activity.rb:82:in `block in <class:CurationActivity>'
app/controllers/stash_engine/admin_datasets_controller.rb:182:in `block (2 levels) in curation_activity_change'
app/controllers/stash_engine/admin_datasets_controller.rb:156:in `curation_activity_change'
app/controllers/application_controller.rb:3:in `process_action'
  TRANSACTION (74.3ms)  ROLLBACK
  ↳ app/controllers/stash_engine/admin_datasets_controller.rb:182:in `block (2 levels) in curation_activity_change'
Completed 500 Internal Server Error in 34306ms (ActiveRecord: 2835.8ms | Allocations: 386061)

**Comment by sfisher** [comment]
I filed ticket https://github.com/CDLUC3/ezid/issues/426 in the EZID repository.  Not an urgent issue for us, but weird new behavior.

**Comment by sfisher** [comment]
After a lot of debugging of the EZID client that we're using, I was able to create similar curl requests like these:

```
# mint ID
curl -i -X POST "https://ezid.cdlib.org/shoulder/doi:10.5072/FK2" -H "Content-Type: text/plain; charset=UTF-8" --data "_status: reserved" -u "user:pass"

# update and publish ID
curl -i -X POST "https://ezid.cdlib.org/id/doi:10.5072/FK26D60D7Z"    -H "Content-Type: text/plain; charset=UTF-8"     --data-binary "@ezid_text.txt"     -u "user:pass"
```

[ezid_text.txt](https://github.com/CDL-Dryad/dryad-product-roadmap/files/11605832/ezid_text.txt)

I eventually worked out that I was able to mint IDs on both the development machine and also a local machine being used for development.  However I was unable to update metadata and publish from a development machine, but only from the official development machine.

IDK if it has something to do with the localhost URLs it created or something else.  I also think possibly EZID expires some of the test identifiers that get minted which throws confusion in.

In any case, I was able to do it with curl and also **only** from the development machine and not locally.  It seems like something has changed from before since I don't think we ran into this problem before.

It's probably OK as long as we know about the limitation and only try publishing from the real development machine.
