### ISSUE TITLE
undefined method `zenodo_presigned_url' for StashEngine::DataFile

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2729]
We're some of these emails weekly (probably 3-5) about `zenodo_presigned_url` not existing for DataFiles. It correctly doesn't exist because we serve data files ourselves and wouldn't be sending people to zenodo to retrieve these files when things are in review. We only generate zenodo presigned for software or supplemental files.

There shouldn't really be any datafiles sent to zenodo until publication.

This may only be a bot hitting URLs.  I'm seeing this user agent in the more recent ones. `Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; PetalBot;+https://webmaster.petalsearch.com/site/petalbot)`

Example below:

It seems to be including a long string in the share parameter that doesn't look valid.  It may also be attempting to try different IDs that don't exist in links or other things.

```
[Dryad Exception]downloads#zenodo_file (NoMethodError) "undefined method `zenodo_presigned_url' for #<StashEngine::DataF..

A NoMethodError occurred in downloads#zenodo_file:

  undefined method `zenodo_presigned_url' for #<StashEngine::DataFile id: 718, upload_file_name: "raw_data.zip", upload_content_type: "application/zip", upload_file_size: 864994783, resource_id: 183, upload_updated_at: nil, created_at: "2019-06-18 13:23:18.000000000 +0000", updated_at: "2023-03-21 22:28:34.000000000 +0000", file_state: "created", url: "https://dryad-assetstore-east.s3.amazonaws.com/101...", status_code: 200, timed_out: false, original_url: nil, cloud_service: nil, digest: "9e6e845832c55acd0997451e23493113", digest_type: "md5", description: "Salmon salar gut microbiome sequences. Samples are...", original_filename: nil, type: "StashEngine::DataFile", compressed_try: 0>
Did you mean?  zenodo_replication_url
  app/controllers/stash_engine/downloads_controller.rb:122:in `zenodo_file'


-------------------------------
Request:
-------------------------------

  * URL        : https://datadryad.org/stash/downloads/zenodo_file/718?share=<redacted>
  * HTTP Method: GET
  * IP address : 114.119.145.187
  * Parameters : {"share"=>"<redacted>", "controller"=>"stash_engine/downloads", "action"=>"zenodo_file", "file_id"=>"718"}
  * Timestamp  : 2023-08-09 07:59:49 UTC
  * Server : uc3-dryadui01x2-prd
    * Rails root : /apps/dryad/apps/ui/releases/20230804003035
  * Process: 5657

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {}

-------------------------------
Environment:
-------------------------------

  * GATEWAY_INTERFACE                                       : CGI/1.2
    * HTTP_ACCEPT                                             : text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    * HTTP_ACCEPT_ENCODING                                    : gzip, deflate
    * HTTP_ACCEPT_LANGUAGE                                    : en
    * HTTP_CONNECTION                                         : Keep-Alive
    * HTTP_HOST                                               : localhost:3000
    * HTTP_REFERER                                            : https://datadryad.org/stash/share/<redacted>
    * HTTP_USER_AGENT                                         : Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; PetalBot;+https://webmaster.petalsearch.com/site/petalbot)
    * HTTP_VERSION                                            : HTTP/1.1
    * HTTP_X_AMZN_TRACE_ID                                    : Root=1-64d34775-4f5bed967459a7671c7e90f6
    * HTTP_X_FORWARDED_FOR                                    : 114.119.145.187, 172.30.11.5
    * HTTP_X_FORWARDED_HOST                                   : datadryad.org
    * HTTP_X_FORWARDED_PORT                                   : 443
    * HTTP_X_FORWARDED_PROTO                                  : https
    * HTTP_X_FORWARDED_SERVER                                 : datadryad.org
    * ORIGINAL_FULLPATH                                       : /stash/downloads/zenodo_file/718?share=<redacted>
    * ORIGINAL_SCRIPT_NAME                                    :
    * PATH_INFO                                               : /stash/downloads/zenodo_file/718
    * QUERY_STRING                                            : share=<redacted>
    * REMOTE_ADDR                                             : 127.0.0.1
    * REQUEST_METHOD                                          : GET
    * REQUEST_PATH                                            : /stash/downloads/zenodo_file/718
    * REQUEST_URI                                             : /stash/downloads/zenodo_file/718?share=<redacted>
    * ROUTES_60300_SCRIPT_NAME                                :
    * SCRIPT_NAME                                             :
    * SERVER_NAME                                             : localhost
    * SERVER_PORT                                             : 3000
    * SERVER_PROTOCOL                                         : HTTP/1.1
    * SERVER_SOFTWARE                                         : puma 6.1.0 The Way Up
    * action_controller.instance                              : #<StashEngine::DownloadsController:0x00007f9760c7b330>
    * action_dispatch.authenticated_encrypted_cookie_salt     : [FILTERED]
    * action_dispatch.backtrace_cleaner                       : #<Rails::BacktraceCleaner:0x00007f9776c5d7c0>
    * action_dispatch.content_security_policy                 : #<ActionDispatch::ContentSecurityPolicy:0x00007f976809ef00>
    * action_dispatch.content_security_policy_nonce_directives:
    * action_dispatch.content_security_policy_nonce_generator :
    * action_dispatch.content_security_policy_report_only     : false
    * action_dispatch.cookies                                 : #<ActionDispatch::Cookies::CookieJar:0x00007f9760c7fc78>
    * action_dispatch.cookies_digest                          :
    * action_dispatch.cookies_rotations                       : #<ActiveSupport::Messages::RotationConfiguration:0x00007f977e6ddd38>
    * action_dispatch.cookies_same_site_protection            : #<Proc:0x00007f976320aad8 /apps/dryad/apps/ui/shared/bundle/ruby/3.0.0/gems/railties-6.1.7.3/lib/rails/application.rb:636>
    * action_dispatch.cookies_serializer                      : json
    * action_dispatch.encrypted_cookie_cipher                 : [FILTERED]
    * action_dispatch.encrypted_cookie_salt                   : [FILTERED]
    * action_dispatch.encrypted_signed_cookie_salt            : [FILTERED]
    * action_dispatch.http_auth_salt                          : [FILTERED]
    * action_dispatch.key_generator                           : #<ActiveSupport::CachingKeyGenerator:0x00007f97630ec598>
    * action_dispatch.logger                                  : #<ActiveSupport::Logger:0x00007f9775c97480>
    * action_dispatch.parameter_filter                        : [:password, :passw, :secret, :token, :_key, :crypt, :salt, :certificate, :otp, /^((?-mix:client_secret|authentication_token|access_token|refresh_token|code))$/]
    * action_dispatch.permissions_policy                      :
    * action_dispatch.redirect_filter                         : []
    * action_dispatch.remote_ip                               : 114.119.145.187
    * action_dispatch.request.content_type                    :
    * action_dispatch.request.formats                         : [#<Mime::Type:0x00007f9779acda10 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=-1329242065692261304>]
    * action_dispatch.request.parameters                      : {"share"=>"<redacted>", "controller"=>"stash_engine/downloads", "action"=>"zenodo_file", "file_id"=>"718"}
    * action_dispatch.request.path_parameters                 : {:controller=>"stash_engine/downloads", :action=>"zenodo_file", :file_id=>"718"}
    * action_dispatch.request.query_parameters                : {"share"=>"<redacted>"}
    * action_dispatch.request.request_parameters              : {}
    * action_dispatch.request.unsigned_session_cookie         : {}
    * action_dispatch.request_id                              : e71f9135-e88b-4a63-8b61-d82751008667
    * action_dispatch.routes                                  : #<ActionDispatch::Routing::RouteSet:0x00007f9775c93f10>
    * action_dispatch.secret_key_base                         : [FILTERED]
    * action_dispatch.show_detailed_exceptions                : false
    * action_dispatch.show_exceptions                         : true
    * action_dispatch.signed_cookie_digest                    :
    * action_dispatch.signed_cookie_salt                      : [FILTERED]
    * action_dispatch.use_authenticated_cookie_encryption     : [FILTERED]
    * action_dispatch.use_cookies_with_metadata               : true
    * puma.config                                             : #<Puma::Configuration:0x00007f977e4cad48>
    * puma.request_body_wait                                  : 0.0034637451171875
    * puma.socket                                             : #<TCPSocket:0x00007f9762f6b048>
    * rack.after_reply                                        : []
    * rack.attack.called                                      : true
    * rack.attack.throttle_data                               : {"all_requests_by_IP"=>{:discriminator=>"114.119.145.187", :count=>1, :period=>60, :limit=>120, :epoch_time=>1691567989}}
    * rack.errors                                             : #<IO:0x00007f978aa817d0>
    * rack.hijack                                             : #<Puma::Client:0x00007f9762f6b020>
    * rack.hijack?                                            : true
    * rack.input                                              : #<Puma::NullIO:0x00007f977e4f6920>
    * rack.multiprocess                                       : false
    * rack.multithread                                        : true
    * rack.request.cookie_hash                                : {}
    * rack.request.query_hash                                 : {"share"=>"<redacted>"}
    * rack.request.query_string                               : share=<redacted>
    * rack.run_once                                           : false
    * rack.session                                            : #<ActionDispatch::Request::Session:0x00007f9760c9c170>
    * rack.session.options                                    : #<ActionDispatch::Request::Session::Options:0x00007f9760c9c120>
    * rack.tempfiles                                          : []
    * rack.url_scheme                                         : https
    * rack.version                                            : [1, 6]
    * warden                                                  : Warden::Proxy:85838820 @config={:default_scope=>nil, :scope_defaults=>{}, :default_strategies=>{}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x00007f977667b1b8>}

-------------------------------
Backtrace:
-------------------------------

  app/controllers/stash_engine/downloads_controller.rb:122:in `zenodo_file'
  app/controllers/application_controller.rb:3:in `process_action'

```

**Comment by sfisher** [comment]
PS.  Seems like PetalBot is owned by Huawei for whatever that is worth.

**Comment by ryscher** [comment]
Putting into backlog because we haven't seen the issue in a while.
