### ISSUE TITLE
Verify our DataCite XML funder generation ROR & X-Rref both work

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2859]
This may be very little work aside from verifying.  Both types of funders should be able to be added to the DataCite.xml if they are both present (or one or the other).

The point is that items that cannot be converted from XRef to ROR can still get sent to datacite for the few unmatched items after the conversion.

I suspect this may already work correctly, but verify.

https://docs.google.com/document/d/1svrl8I1yU6ZS1p45pupWSWSVe63m796XjrAEq0hRp_4/edit

**Comment by sfisher** [comment]
I verified that the DataCite XML works.

it produces something like this:

```
<fundingReferences>
  <fundingReference>
    <funderName>Singapore General Hospital</funderName>
    <funderIdentifier funderIdentifierType="ROR">https://ror.org/036j6sg82</funderIdentifier>
    <awardNumber>393</awardNumber>
  </fundingReference>
</fundingReferences>
<contributors>
  <contributor contributorType="Sponsor">
    <contributorName>National University of Singapore</contributorName>
  </contributor>
</contributors>
```

It seems a bit odd that it names them both as funder reference and contributor, but I think that is OK and we've probably been doing that for a while.

**Comment by ahamelers** [comment]
The sponsor contributor comes from the Research facility field, I believe!

**Comment by sfisher** [comment]
Ok.  This seems to create the correct output for Merritt, but I'm now getting errors trying to run the datacite update for metadata.  I'm not quite sure why this doesn't work but the output for merritt seemed to.

```bash
$ RAILS_ENV=development bundle exec rails datacite_target:update_dryad

Running main rspec tasks...
 -- environment development
1/12: updating 10.7959/dryad.pzgmsbh1
2/12: updating 10.7959/dryad.hhmgqnp0
rails aborted!
Nokogiri::XML::SyntaxError: 25:0: ERROR: Element '{http://datacite.org/schema/kernel-4}funderIdentifier', attribute 'funderIdentifierType': [facet 'enumeration'] The value 'ROR' is not an element of the set {'ISNI', 'GRID', 'Crossref Funder ID', 'Other'}.
/Users/sfisher/workspace/direct-to-cdl-dryad/dryad-app/lib/stash/repo/validating_xml_builder.rb:30:in `validate'
/Users/sfisher/workspace/direct-to-cdl-dryad/dryad-app/lib/stash/repo/validating_xml_builder.rb:19:in `contents'
/Users/sfisher/workspace/direct-to-cdl-dryad/dryad-app/lib/stash/doi/id_gen.rb:61:in `update_identifier_metadata!'
/Users/sfisher/workspace/direct-to-cdl-dryad/dryad-app/lib/tasks/dash_updater.rb:31:in `submit_id_metadata'
/Users/sfisher/workspace/direct-to-cdl-dryad/dryad-app/lib/tasks/datacite_target.rake:35:in `block (3 levels) in <main>'
/Users/sfisher/workspace/direct-to-cdl-dryad/dryad-app/lib/tasks/datacite_target.rake:29:in `each_with_index'
/Users/sfisher/workspace/direct-to-cdl-dryad/dryad-app/lib/tasks/datacite_target.rake:29:in `block (2 levels) in <main>'
Tasks: TOP => datacite_target:update_dryad
(See full trace by running task with --trace)
```
