### ISSUE TITLE
Error on author affiliation

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#311]
I'm not sure how this is triggered, but I got about 4 or more emails about this as an error when we did the test of submitting to Merritt.   
![image](https://user-images.githubusercontent.com/105433/57725080-1f348c00-7641-11e9-858e-69b96f8ea6e8.png)

https://docs.google.com/spreadsheets/d/1-lNaGsyULm7uz8amZ7GTemLd8_QaT6dQR5qKDwJC-o8/edit#gid=0

```
A NoMethodError occurred in authors#create:



  undefined method `affiliation=' for nil:NilClass

  /apps/dryad/apps/ui/releases/stash/stash_datacite/app/controllers/stash_datacite/authors_controller.rb:81:in `process_affiliation'





-------------------------------

Request:

-------------------------------



  * URL        : http://dryad-stg.cdlib.org/stash_datacite/authors/create

  * HTTP Method: POST

  * IP address : 128.48.204.211

  * Parameters : {"utf8"=>"✓", "authenticity_token"=>"J/jYg8v8nQPdEEwR58OTN8qRMIxNgxiqCvAh0Nw2sjeb8WsRKnBnddaUpJOENfcPfb2PptuWKbBvzD3wuJ3New==", "author"=>{"author_first_name"=>"Henrietta", "author_last_name"=>"Pussycat", "affiliation"=>{"long_name"=>"", "id"=>"", "ror_id"=>""}, "author_email"=>"", "resource_id"=>"391", "id"=>""}, "form_id"=>"new_author_e09dbc15-9feb-483f-8d46-58efac7626e7", "controller"=>"stash_datacite/authors", "action"=>"create"}

  * Timestamp  : 2019-05-14 16:31:22 UTC

  * Server : uc3-dryad-stg

  * Rails root : /apps/dryad/apps/ui/releases/20190514160619

  * Process: 28521



-------------------------------

Session:

-------------------------------



  * session id: "6588f80983aa00530469686e19ab0671"

  * data: {"session_id"=>"6588f80983aa00530469686e19ab0671",

   "_csrf_token"=>"vAmzkuGM+nYLhOiCY/ZkOLcsvyqWFTEaZTwcIGSrf0w=",

   "search"=>{"id"=>nil},

   "user_id"=>57,

   "show_migrate"=>true}



-------------------------------

Environment:

-------------------------------



  * CONTENT_LENGTH                                 : 442

  * CONTENT_TYPE                                   : application/x-www-form-urlencoded; charset=UTF-8

  * HTTP_ACCEPT                                    : */*;q=0.5, text/javascript, application/javascript, application/ecmascript, application/x-ecmascript

  * HTTP_ACCEPT_ENCODING                           : gzip, deflate, br

  * HTTP_ACCEPT_LANGUAGE                           : en-US,en;q=0.9

  * HTTP_COOKIE                                    : _ga=GA1.2.1916518048.1555621427; __utmz=29472237.1556129916.5.2.utmccn=(referral)|utmcsr=cdlib-stage.cdlib.org|utmcct=/services/collections/massdig/books.html|utmcmd=referral; __utma=29472237.1916518048.1555621427.1557164643.1557255024.13; _gid=GA1.2.475899002.1557850827; _shibsession_64656661756c7468747470733a2f2f646173682d7374672e63646c69622e6f72672f73686962626f6c657468=_0a3a98b03cded11342b906341a79d9de; _dash2_session=b01uUHRweFVzSmtjSlkzMlhkQll1bnREYmZ5dW5tQTNqOXNIS1l4Z1NpUEM5elBrSmI3aERTdmxOZU5NRTB4NGozbE5pbXdSSVNRVU82eHZFWTFuYVViZWRBbm42Y25EU0VMVE43Q0pZREF1b0d6UG50RjdmUmFocHJxR0FIeFE1VWxaOEVhMGZIQk1UcWQ3akNLT1c5TE90VHEwZGVGWWs1dEx6VlIzc1ZRQlZOSm5vdno1aG5EMlJWaHdTMTVBMWJTUkc5cTJLVWN2TmRkQ1ZrTnZDVGxraHEvREdKSDNhTnNDNmEyNWh0ND0tLVZTTVh2MWpJVXlESTNlUUVLaXNTNWc9PQ%3D%3D--2a2702fe15f459f9599540c769cdc1d73f8b1976

  * HTTP_HOST                                      : uc3-dryad-stg.cdlib.org:3000

  * HTTP_ORIGIN                                    : https://dryad-stg.cdlib.org

  * HTTP_REFERER                                   : https://dryad-stg.cdlib.org/stash/metadata_entry_pages/find_or_create?resource_id=391

  * HTTP_USER_AGENT                                : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36

  * HTTP_VERSION                                   : HTTP/1.1

  * HTTP_X_CSRF_TOKEN                              : y3VL8GgrE1AhPh0QcrtfHxRV3Uq0LsQXeVrFzPjK5zF3fPhiiafpJiq69ZIRTTsno3liYCI79Q0cZtnsnGGYfQ==

  * HTTP_X_FORWARDED_FOR                           : 128.48.204.211

  * HTTP_X_FORWARDED_HOST                          : dryad-stg.cdlib.org

  * HTTP_X_FORWARDED_SERVER                        : dryad-stg.cdlib.org

  * HTTP_X_REQUESTED_WITH                          : XMLHttpRequest

  * ORIGINAL_FULLPATH                              : /stash_datacite/authors/create

  * ORIGINAL_SCRIPT_NAME                           :

  * PASSENGER_CONNECT_PASSWORD                     : [FILTERED]

  * PATH_INFO                                      : /authors/create

  * QUERY_STRING                                   :

  * REMOTE_ADDR                                    : 172.31.35.49

  * REMOTE_PORT                                    : 50082

  * REQUEST_METHOD                                 : POST

  * REQUEST_URI                                    : /stash_datacite/authors/create

  * ROUTES_47335543030740_SCRIPT_NAME              : /stash_datacite

  * ROUTES_47335551813060_SCRIPT_NAME              : /stash

  * ROUTES_47335573738420_SCRIPT_NAME              :

  * SCRIPT_NAME                                    : /stash_datacite

  * SERVER_NAME                                    : uc3-dryad-stg.cdlib.org

  * SERVER_PORT                                    : 3000

  * SERVER_PROTOCOL                                : HTTP/1.1

  * SERVER_SOFTWARE                                : nginx/1.15.8 Phusion_Passenger/6.0.2

  * action_controller.instance                     : #<StashDatacite::AuthorsController:0x00007f26dec82790>

  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x0000561a5436ac30>

  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x00007f26dec7e988>

  * action_dispatch.cookies_digest                 :

  * action_dispatch.cookies_serializer             : json

  * action_dispatch.encrypted_cookie_salt          : encrypted cookie

  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie

  * action_dispatch.http_auth_salt                 : http authentication

  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x0000561a588d52c0>

  * action_dispatch.logger                         : #<ActiveSupport::Logger:0x0000561a581470f8>

  * action_dispatch.parameter_filter               : [:password, /^((?-mix:client_secret|code|authentication_token|access_token|refresh_token))$/]

  * action_dispatch.redirect_filter                : []

  * action_dispatch.remote_ip                      : 128.48.204.211

  * action_dispatch.request.accepts                : [#<Mime::Type:0x0000561a539521f8 @synonyms=["application/javascript", "application/x-javascript"], @symbol=:js, @string="text/javascript", @hash=2640983092325599125>, #<Mime::Type:0x00007f26dec80760 @synonyms=[], @symbol=nil, @string="application/ecmascript", @hash=2670060924704089007>, #<Mime::Type...

  * action_dispatch.request.content_type           : application/x-www-form-urlencoded

  * action_dispatch.request.formats                : [#<Mime::Type:0x0000561a539521f8 @synonyms=["application/javascript", "application/x-javascript"], @symbol=:js, @string="text/javascript", @hash=2640983092325599125>, #<Mime::Type:0x00007f26dec80760 @synonyms=[], @symbol=nil, @string="application/ecmascript", @hash=2670060924704089007>, #<Mime::Type...

  * action_dispatch.request.parameters             : {"utf8"=>"✓", "authenticity_token"=>"J/jYg8v8nQPdEEwR58OTN8qRMIxNgxiqCvAh0Nw2sjeb8WsRKnBnddaUpJOENfcPfb2PptuWKbBvzD3wuJ3New==", "author"=>{"author_first_name"=>"Henrietta", "author_last_name"=>"Pussycat", "affiliation"=>{"long_name"=>"", "id"=>"", "ror_id"=>""}, "author_email"=>"", "resource_id"=>"3...

  * action_dispatch.request.path_parameters        : {:controller=>"stash_datacite/authors", :action=>"create"}

  * action_dispatch.request.query_parameters       : {}

  * action_dispatch.request.request_parameters     : {"utf8"=>"✓", "authenticity_token"=>"J/jYg8v8nQPdEEwR58OTN8qRMIxNgxiqCvAh0Nw2sjeb8WsRKnBnddaUpJOENfcPfb2PptuWKbBvzD3wuJ3New==", "author"=>{"author_first_name"=>"Henrietta", "author_last_name"=>"Pussycat", "affiliation"=>{"long_name"=>"", "id"=>"", "ror_id"=>""}, "author_email"=>"", "resource_id"=>"3...

  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"6588f80983aa00530469686e19ab0671", "_csrf_token"=>"vAmzkuGM+nYLhOiCY/ZkOLcsvyqWFTEaZTwcIGSrf0w=", "search"=>{"id"=>nil}, "user_id"=>57, "show_migrate"=>true}

  * action_dispatch.request_id                     : 071a3f10-f95b-40d3-a055-cc5784f3f7ff

  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x0000561a547487a8>

  * action_dispatch.secret_key_base                : 603e98fef5b5671da9413f0cac2409dbc7e8b7fd420c75ff586be51e597740d48b5e259ea4960d3507b513b1da2762757eb1f2dcd2f785dc8eb42207c1f736a9

  * action_dispatch.secret_token                   :

  * action_dispatch.show_detailed_exceptions       : false

  * action_dispatch.show_exceptions                : true

  * action_dispatch.signed_cookie_salt             : signed cookie

  * rack.errors                                    : #<IO:0x0000561a52115860>

  * rack.hijack                                    : #<Proc:0x00007f26dec8f7b0@/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:84 (lambda)>

  * rack.hijack?                                   : true

  * rack.input                                     : #<PhusionPassenger::Utils::TeeInput:0x00007f26dec8f990>

  * rack.multiprocess                              : true

  * rack.multithread                               : false

  * rack.request.cookie_hash                       : {"_ga"=>"GA1.2.1916518048.1555621427", "__utmz"=>"29472237.1556129916.5.2.utmccn=(referral)|utmcsr=cdlib-stage.cdlib.org|utmcct=/services/collections/massdig/books.html|utmcmd=referral", "__utma"=>"29472237.1916518048.1555621427.1557164643.1557255024.13", "_gid"=>"GA1.2.475899002.1557850827", "_shib...

  * rack.request.cookie_string                     : _ga=GA1.2.1916518048.1555621427; __utmz=29472237.1556129916.5.2.utmccn=(referral)|utmcsr=cdlib-stage.cdlib.org|utmcct=/services/collections/massdig/books.html|utmcmd=referral; __utma=29472237.1916518048.1555621427.1557164643.1557255024.13; _gid=GA1.2.475899002.1557850827; _shibsession_64656661756c7468747470733a2f2f646173682d7374672e63646c69622e6f72672f73686962626f6c657468=_0a3a98b03cded11342b906341a79d9de; _dash2_session=b01uUHRweFVzSmtjSlkzMlhkQll1bnREYmZ5dW5tQTNqOXNIS1l4Z1NpUEM5elBrSmI3aERTdmxOZU5NRTB4NGozbE5pbXdSSVNRVU82eHZFWTFuYVViZWRBbm42Y25EU0VMVE43Q0pZREF1b0d6UG50RjdmUmFocHJxR0FIeFE1VWxaOEVhMGZIQk1UcWQ3akNLT1c5TE90VHEwZGVGWWs1dEx6VlIzc1ZRQlZOSm5vdno1aG5EMlJWaHdTMTVBMWJTUkc5cTJLVWN2TmRkQ1ZrTnZDVGxraHEvREdKSDNhTnNDNmEyNWh0ND0tLVZTTVh2MWpJVXlESTNlUUVLaXNTNWc9PQ%3D%3D--2a2702fe15f459f9599540c769cdc1d73f8b1976

  * rack.request.form_hash                         : {"utf8"=>"✓", "authenticity_token"=>"J/jYg8v8nQPdEEwR58OTN8qRMIxNgxiqCvAh0Nw2sjeb8WsRKnBnddaUpJOENfcPfb2PptuWKbBvzD3wuJ3New==", "author"=>{"author_first_name"=>"Henrietta", "author_last_name"=>"Pussycat", "affiliation"=>{"long_name"=>"", "id"=>"", "ror_id"=>""}, "author_email"=>"", "resource_id"=>"3...

  * rack.request.form_input                        : #<PhusionPassenger::Utils::TeeInput:0x00007f26dec8f990>

  * rack.request.form_vars                         : [FILTERED]

  * rack.request.query_hash                        : {}

  * rack.request.query_string                      :

  * rack.run_once                                  : false

  * rack.session                                   : #<ActionDispatch::Request::Session:0x00007f26dec8aa30>

  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x00007f26dec8a9e0>

  * rack.url_scheme                                : http

  * rack.version                                   : [1, 2]

  * warden                                         : Warden::Proxy:69902461588500 @config={:default_scope=>nil, :scope_defaults=>{}, :default_strategies=>{}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x0000561a57cc5a48>}



-------------------------------

Backtrace:

-------------------------------



  /apps/dryad/apps/ui/releases/stash/stash_datacite/app/controllers/stash_datacite/authors_controller.rb:81:in `process_affiliation'

  /apps/dryad/apps/ui/releases/stash/stash_datacite/app/controllers/stash_datacite/authors_controller.rb:24:in `block in create'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/mime_responds.rb:212:in `respond_to'

  /apps/dryad/apps/ui/releases/stash/stash_datacite/app/controllers/stash_datacite/authors_controller.rb:23:in `create'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/implicit_render.rb:4:in `send_action'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/abstract_controller/base.rb:198:in `process_action'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/rendering.rb:10:in `process_action'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/abstract_controller/callbacks.rb:20:in `block in process_action'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:117:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:505:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:92:in `__run_callbacks__'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/abstract_controller/callbacks.rb:19:in `process_action'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/rescue.rb:29:in `process_action'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:164:in `block in instrument'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:164:in `instrument'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/instrumentation.rb:30:in `process_action'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/railties/controller_runtime.rb:18:in `process_action'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/abstract_controller/base.rb:137:in `process'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.11/lib/action_view/rendering.rb:30:in `process'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal.rb:196:in `dispatch'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_controller/metal.rb:237:in `block in action'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:43:in `serve'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:43:in `block in serve'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:30:in `each'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:30:in `serve'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:817:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/engine.rb:518:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/railtie.rb:194:in `public_send'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/railtie.rb:194:in `method_missing'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/routing/mapper.rb:51:in `serve'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:43:in `block in serve'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:30:in `each'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/journey/router.rb:30:in `serve'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/routing/route_set.rb:817:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:190:in `call!'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:168:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:190:in `call!'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:168:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/builder.rb:63:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/exception_notification-4.3.0/lib/exception_notification/rack.rb:41:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/etag.rb:24:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/conditionalget.rb:38:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/head.rb:13:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/params_parser.rb:27:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/flash.rb:260:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/session/abstract/id.rb:225:in `context'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/session/abstract/id.rb:220:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/cookies.rb:560:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/query_cache.rb:36:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:88:in `__run_callbacks__'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/callbacks.rb:27:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/rack/logger.rb:38:in `call_app'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/rack/logger.rb:20:in `block in call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/tagged_logging.rb:68:in `block in tagged'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/tagged_logging.rb:26:in `tagged'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/tagged_logging.rb:68:in `tagged'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/rack/logger.rb:20:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/request_id.rb:21:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/methodoverride.rb:22:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/runtime.rb:18:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/static.rb:120:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/static.rb:120:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/static.rb:120:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/sendfile.rb:113:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/engine.rb:518:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.11/lib/rails/application.rb:165:in `call'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'

  /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by briri** [comment]
probably some code that leaked in when we deployed to stage this morning

**Comment by sfisher** [comment]
I think Brian fixed this, so closing.
