### ISSUE TITLE
Unable to set curation status to embargoed

### ISSUE THREAD

**Issue by briri** [CDL-Dryad/dryad-product-roadmap#376]
Getting the following error when setting a dataset curation status to embargoed:

```shell
Completed 500 Internal Server Error in 818ms (ActiveRecord: 28.2ms)

Stash::Doi::DataciteError (DataCite failed to update metadata for resource 843):
  /apps/dryad/apps/ui/releases/stash/stash_engine/lib/stash/doi/datacite_gen.rb:54:in `validate_response'
  /apps/dryad/apps/ui/releases/stash/stash_engine/lib/stash/doi/datacite_gen.rb:32:in `update_metadata'
  /apps/dryad/apps/ui/releases/stash/stash_engine/lib/stash/doi/id_gen.rb:48:in `update_identifier_metadata!'
  /apps/dryad/apps/ui/releases/stash/stash_engine/app/models/stash_engine/curation_activity.rb:130:in `submit_to_datacite'
  /apps/dryad/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb:80:in `block (2 levels) in curation_activity_change'
  /apps/dryad/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb:71:in `curation_activity_change'


  Rendered /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/templates/rescues/_source.erb (6.3ms)
  Rendered /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.7ms)
  Rendered /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (0.6ms)
  Rendered /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (20.4ms)
```

**Comment by briri** [comment]
Also now seeing these as well:
```shell
Completed 500 Internal Server Error in 103ms (ActiveRecord: 20.0ms)

Ezid::IdentifierNotFoundError (bad request - no such identifier):
  /apps/dryad/apps/ui/releases/stash/stash_engine/lib/stash/doi/ezid_gen.rb:42:in `update_metadata'
  /apps/dryad/apps/ui/releases/stash/stash_engine/lib/stash/doi/id_gen.rb:48:in `update_identifier_metadata!'
  /apps/dryad/apps/ui/releases/stash/stash_engine/app/models/stash_engine/curation_activity.rb:131:in `submit_to_datacite'
  /apps/dryad/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb:81:in `block (2 levels) in curation_activity_change'
  /apps/dryad/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb:71:in `curation_activity_change'


  Rendered /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/templates/rescues/_source.erb (6.6ms)
  Rendered /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.9ms)
  Rendered /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (0.8ms)
  Rendered /apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.11/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (22.9ms)
```

**Comment by briri** [comment]
Ok, new changes have shed more light on these issues:

Datacite is reporting a 403 Forbidden error:
```shell
Stash::Doi::DataciteError: DataCite failed to update metadata for resource 1269 -- 
  <OpenStruct body={
      "errors"=>[{"status"=>403, "title"=>"Access is denied"}]
    }, 
    status=403, 
    headers={
      "Date"=>"Tue, 23 Jul 2019 17:36:01 GMT", 
      "Content-Type"=>"text/plain; charset=utf-8", 
      "Connection"=>"keep-alive", 
      "Status"=>"403 Forbidden", 
      "Cache-Control"=>"no-cache", 
      "Vary"=>"Accept-Encoding, Origin", 
      "X-Runtime"=>"0.069506", 
      "X-Credential-Username"=>"[USERNAME]", 
      "X-Request-Id"=>"81f3550b-de9b-4885-9990-340ae7c70548", 
      "X-Powered-By"=>"Phusion Passenger 6.0.2", 
      "Server"=>"nginx/1.15.8 + Phusion Passenger 6.0.2"
    }, 
    url="https://mds.test.datacite.org/metadata"
  >;
/apps/dryad/apps/ui/releases/stash/stash_engine/lib/stash/doi/datacite_gen.rb:60:in `validate_response&#39;
/apps/dryad/apps/ui/releases/stash/stash_engine/lib/stash/doi/datacite_gen.rb:33:in `update_metadata&#39;
```

Ezid 404 Not Found:
```shell
Stash::Doi::IdGen - Unable to submit metadata changes for : 'doi:10.5072/FK2T153561'
Ezid failed to update metadata for resource doi:10.5072/FK2T153561 (bad request - no such identifier) with params: 
{
:status=>"public", :datacite=>"
    <resource xsi:schemaLocation='http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns='http://datacite.org/schema/kernel-4'>
      <identifier identifierType='DOI'>10.5072/FK2T153561</identifier>
      <creators>
        <creator>
          <creatorName>Fritsch, Milan</creatorName>
          <affiliation>UCLOP</affiliation>
        </creator>
      </creators>
      <titles>
        <title>Alias Dolor</title>
      </titles>
      <publisher>UC Office of the President</publisher>
      <publicationYear>2019</publicationYear>
      <language>en</language>
      <resourceType resourceTypeGeneral='Dataset'>dataset</resourceType>
      <sizes>
        <size>45000000 bytes</size>
      </sizes>
      <version>1</version>
      <rightsList>
        <rights rightsURI='https://creativecommons.org/publicdomain/zero/1.0/'>CC0 1.0 Universal (CC0 1.0) Public Domain Dedication</rights>
       </rightsList>
       <descriptions>
         <description descriptionType='Abstract'>Atque voluptatem mollitia. Facere officia molestiae. Et ullam dolorem.</description>
       </descriptions>
    </resource>", 
:target=>"http://dryad-dev.cdlib.org/stash/dataset/doi:10.5072/FK2T153561"
}
```

**Comment by briri** [comment]
Added handling to capture Ezid errors as well and then updated UI to display a message for the curators/admins:
<img width="1004" alt="Screen Shot 2019-07-23 at 3 37 14 PM" src="https://user-images.githubusercontent.com/1204467/61752351-19a1a380-ad60-11e9-8a08-fd0a5f25eaaf.png">
