### ISSUE TITLE
Broken test after merge from master

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#383]
I think this was something someone changed and somehow didn't trigger test problems and got merged into master and now is causing test problems.

```
Failures:

  1) StashEngine::ProposedChange reject! returns the user tenant ID
     Failure/Error: update(rejected: true, user_id: current_user.id)

     ActiveRecord::UnknownAttributeError:
       unknown attribute 'rejected' for StashEngine::ProposedChange.
     # ./app/models/stash_datacite/proposed_change.rb:35:in `reject!'
     # ./spec/db/stash_engine/proposed_change_spec.rb:124:in `block (3 levels) in <module:StashEngine>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `rejected=' for #<StashEngine::ProposedChange:0x007fdcf05aca60>
     #   Did you mean?  reject!
     #   ./app/models/stash_datacite/proposed_change.rb:35:in `reject!'
```

**Comment by briri** [comment]
Think this is due to your local test DB having run the migration before a final change.
