### ISSUE TITLE
Bug: error message at login

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#453]
From UNM "I got to the point where I had authorized the connection of my UNM credentials to my ORCID account, but then received the following error message.

The link associated with this error is: https://dryadx2-prd.cdlib.org/stash/auth/orcid/callback?code=m8eyv2&state=26a06e5db9d91ffd2ac2981aa390b7dfc9f2034ef9d40638

"

**Comment by sfisher** [comment]
“I got to the same error message when following the suggested process - immediately following the entry of my ORCID individual login and password and submitting them. To try to make sure there wasn't some odd cached web content or cookies I cleared both after restarting my browser (Firefox).
This is the URL of the page that is returning the error:
https://dryadx2-prd.cdlib.org/stash/auth/orcid/callback?code=dc7KRF&state=70c9dca9fb2031f46e711002ad7aa44f346238f47d3952ff”

**Comment by briri** [comment]
It worked ok for me from that link @sfisher. I logged in and authorized my ORCID then selected UCOP and logged into our IdP. 
Maybe something specific to the UNM?

**Comment by sfisher** [comment]
Yeah, we determined that it's not the form of the URL or anything we can tell.  Seems to only happen with UNM.  I can't find any errors in the logs, either.  I thought we would've gotten one with  the "We're sorry, but something went wrong" which is some kind of Rails error.

Super annoying that it's not logged.  It logged a bunch of other problems in the logs, but not that one as far as I can tell.

**Comment by sfisher** [comment]
These are some instances of this login I find of this in the apache logs.  One is on prd-2a and the others are on 2c.  Strangely, the only one that shows a problem is  the first one on 2a which gets a 500 response in return.  The others show a 302 redirect response.  I don't believe the SSL cert lines are any problem, either.

```
dryad@uc3-dryaduix2-prd-2a:~/apps/apache/logs$ grep -F "/stash/auth/orcid/callback?code=m8eyv2" *_log
dryadx2-prd.cdlib.org-access_log:172.30.3.151 - - [10/Sep/2019:12:41:13 -0700] "GET /stash/auth/orcid/callback?code=m8eyv2&state=26a06e5db9d91ffd2ac2981aa390b7dfc9f2034ef9d40638 HTTP/1.1" 500 1477
dryadx2-prd.cdlib.org-ssl_request_log:[10/Sep/2019:12:41:13 -0700] 172.30.3.151 TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256 "GET /stash/auth/orcid/callback?code=m8eyv2&state=26a06e5db9d91ffd2ac2981aa390b7dfc9f2034ef9d40638 HTTP/1.1" 1477


dryad@uc3-dryaduix2-prd-2c:~/apps/apache/logs$ grep -F "/stash/auth/orcid/callback?code=m8eyv2" *_log
dryadx2-prd.cdlib.org-access_log:172.30.38.59 - - [10/Sep/2019:13:08:51 -0700] "GET /stash/auth/orcid/callback?code=m8eyv2&state=26a06e5db9d91ffd2ac2981aa390b7dfc9f2034ef9d40638 HTTP/1.1" 302 9
dryadx2-prd.cdlib.org-access_log:172.30.3.151 - - [11/Sep/2019:11:57:03 -0700] "GET /stash/auth/orcid/callback?code=m8eyv2&state=26a06e5db9d91ffd2ac2981aa390b7dfc9f2034ef9d40638 HTTP/1.1" 302 9
dryadx2-prd.cdlib.org-access_log:172.30.3.151 - - [11/Sep/2019:14:47:39 -0700] "GET /stash/auth/orcid/callback?code=m8eyv2&state=26a06e5db9d91ffd2ac2981aa390b7dfc9f2034ef9d40638 HTTP/1.1" 302 9
dryadx2-prd.cdlib.org-access_log:172.30.3.151 - - [11/Sep/2019:14:48:00 -0700] "GET /stash/auth/orcid/callback?code=m8eyv2&state=26a06e5db9d91ffd2ac2981aa390b7dfc9f2034ef9d40638 HTTP/1.1" 302 9
dryadx2-prd.cdlib.org-ssl_request_log:[10/Sep/2019:13:08:51 -0700] 172.30.38.59 TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256 "GET /stash/auth/orcid/callback?code=m8eyv2&state=26a06e5db9d91ffd2ac2981aa390b7dfc9f2034ef9d40638 HTTP/1.1" 9
dryadx2-prd.cdlib.org-ssl_request_log:[11/Sep/2019:11:57:03 -0700] 172.30.3.151 TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256 "GET /stash/auth/orcid/callback?code=m8eyv2&state=26a06e5db9d91ffd2ac2981aa390b7dfc9f2034ef9d40638 HTTP/1.1" 9
dryadx2-prd.cdlib.org-ssl_request_log:[11/Sep/2019:14:47:39 -0700] 172.30.3.151 TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256 "GET /stash/auth/orcid/callback?code=m8eyv2&state=26a06e5db9d91ffd2ac2981aa390b7dfc9f2034ef9d40638 HTTP/1.1" 9
dryadx2-prd.cdlib.org-ssl_request_log:[11/Sep/2019:14:48:00 -0700] 172.30.3.151 TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256 "GET /stash/auth/orcid/callback?code=m8eyv2&state=26a06e5db9d91ffd2ac2981aa390b7dfc9f2034ef9d40638 HTTP/1.1" 9
```

**Comment by sfisher** [comment]
I believe this is the error that is preventing login.  Probably some kind of ROR lookup happens during login now and if it fails it prevents login.

```
RuntimeError (Unable to connect to ROR https://api.ror.org/organizations?{:query=>"INFOTEC Research Inc./Applied Earthworks, Inc."}: status: 500):
  /apps/dryad/apps/ui/releases/stash/stash_engine/lib/stash/organization/ror.rb:92:in `query_ror'
  /apps/dryad/apps/ui/releases/stash/stash_engine/lib/stash/organization/ror.rb:47:in `find_first_by_ror_name'
  /apps/dryad/apps/ui/releases/stash/stash_datacite/app/models/stash_datacite/affiliation.rb:64:in `find_by_ror_long_name'
  /apps/dryad/apps/ui/releases/stash/stash_datacite/app/models/stash_datacite/affiliation.rb:48:in `from_long_name'
  /apps/dryad/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/sessions_controller.rb:131:in `block in handle_orcid_employments'
  /apps/dryad/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/sessions_controller.rb:130:in `map'
  /apps/dryad/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/sessions_controller.rb:130:in `handle_orcid_employments'
  /apps/dryad/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/sessions_controller.rb:21:in `orcid_callback'
```
