### ISSUE TITLE
SMTP TO address may not be blank

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#490]
It seems like we are trying to send a mail (publishing?) and no authors have an email address or there is some problem in that logic and the TO address is blank.

```An ArgumentError occurred in admin_datasets#curation_activity_change:



  SMTP To address may not be blank: []

  /apps/dryad/apps/ui/releases/stash/stash_engine/app/models/stash_engine/curation_activity.rb:169:in `block in email_orcid_invitations'





-------------------------------

Request:

-------------------------------



  * URL        : https://datadryad.org/stash/curation_activity_change/34652

  * HTTP Method: POST

  * IP address : 104.10.133.166

  * Parameters : {"utf8"=>"✓", "resource"=>{"curation_activity"=>{"status"=>"published", "note"=>""}, "publication_date"=>""}, "commit"=>"Submit", "controller"=>"stash_engine/admin_datasets", "action"=>"curation_activity_change", "id"=>"34652"}

  * Timestamp  : 2019-09-18 21:42:04 UTC

  * Server : uc3-dryaduix2-prd-2c

  * Rails root : /apps/dryad/apps/ui/releases/20190917175235

  * Process: 8758



-------------------------------

Session:

-------------------------------



  * session id: [FILTERED]

  * data: {"session_id"=>"eac0b9c71c5d3eba26c93aaa7d6c0080",

   "_csrf_token"=>"dSG/AaWemUstYGDaYd/KsEkrrNHsqjjczTuljuD6OWs=",

   "search"=>{"id"=>nil},

   "user_id"=>45960,

   "show_migrate"=>true,

   "return_to_path"=>

    "https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=r9162p5&commit=Search&utf8=%E2%9C%93"}



-------------------------------

Environment:

-------------------------------



  * CONTENT_LENGTH                                 : 157

  * CONTENT_TYPE                                   : application/x-www-form-urlencoded; charset=UTF-8

  * HTTP_ACCEPT                                    : */*;q=0.5, text/javascript, application/javascript, application/ecmascript, application/x-ecmascript

  * HTTP_ACCEPT_ENCODING                           : gzip, deflate, br

  * HTTP_ACCEPT_LANGUAGE                           : en-US,en;q=0.9

  * HTTP_COOKIE                                    : __utmz=260151704.1564159617.234.2.utmcsr=daringfireball.net|utmccn=(referral)|utmcmd=referral|utmcct=/projects/markdown/dingus; uvts=b4e3d4cd-9741-4839-75c8-9c4798d6ea65; __utma=260151704.861099230.1558013536.1568742588.1568747494.389; _ga=GA1.2.861099230.1558013536; _gid=GA1.2.1724426143.1568751185; _gat=1; AWSALB=O45w9UaT+k8L9NJLmyRq5VQisVRK1cnOmR6MWlnqgVDnZ8MmMLaifVmazd02h4rQUAEeikAds4a/Zg1gMwMZ1PWLASH+8dTZToYfKT2+K/WdO/y7YXAWQ3I6DeoJ; _dash2_session=N0V1VmxuSkRuRjZCUE5RbkwzcFBsbGtHY2JXVUg0RDQ5Szc1cGtraVYzWkpzTkRHaTNzMVN0V1FrVkRPS1FvUXhIVjBXSENPUjZBSE1qVE9kZ0dPR09zQ1ZZbmFpZjR5MlhsRTJZdE5zbVQ4VmNmRkdtWTZ6a1RrazY1dmU1ZFpROEw2MmVmUGd2bkdvcko5NWs3NlAzTHhBeHgwZUNRcm03UWlEQjFtaFUrcElqTk9WQmR4OVg5YWVGU043VjB5Q1RwVUU2cTl3ZHhGY0poWit4cXR5ZVd5cUxXQUs2QjdVRXF1Zk9aTGlHRHpBKzZyVHVJWko0djZyQnUyNjE1aTlDZVJhYXFLcHB4eHlTM3NKek96NEdIaE5Jd2JDUHRLRGdDMVRqbUhGUVZNZU5HT3F5Q3pteTlUc0swV01hT0lmT3hONU1zVGZrSkxEeFNQVVkyYXBzRnJoL2o2SXRIcndwekJaT2J3OGRtV1pqMDg2WGRtS1FCUHE3QzRzWXRZVVVESEZrR09zdjNIaUFnd1Y2d3dIdz09LS1oL2Jma2tZWWhKY2tVVzcrZnA0dEZBPT0%3D--18c9b34fa219d1a9fb7bf67e047f2752ea68bf08

  * HTTP_HOST                                      : localhost:3000

  * HTTP_ORIGIN                                    : https://datadryad.org

  * HTTP_REFERER                                   : https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=r9162p5&commit=Search&utf8=%E2%9C%93

  * HTTP_SEC_FETCH_MODE                            : cors

  * HTTP_SEC_FETCH_SITE                            : same-origin

  * HTTP_USER_AGENT                                : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

  * HTTP_VERSION                                   : HTTP/1.1

  * HTTP_X_AMZN_TRACE_ID                           : Root=1-5d82a4aa-8c6e36414dd4a54c584e4bb2

  * HTTP_X_CSRF_TOKEN                              : N3tA2yG/xz+M96c63K9yovsIMQMv9XjH6LW99mj53p5CWv/ahCFedKGXx+C9cLgSsiOd0sNfQBsljhh4iAPn9Q==

  * HTTP_X_FORWARDED_FOR                           : 104.10.133.166

  * HTTP_X_FORWARDED_HOST                          : datadryad.org

  * HTTP_X_FORWARDED_PORT                          : 443

  * HTTP_X_FORWARDED_PROTO                         : https

  * HTTP_X_FORWARDED_SERVER                        : datadryad.org

  * HTTP_X_REQUESTED_WITH                          : XMLHttpRequest

  * ORIGINAL_FULLPATH                              : /stash/curation_activity_change/34652

  * ORIGINAL_SCRIPT_NAME                           :

  * PASSENGER_CONNECT_PASSWORD                     : [FILTERED]

  * PATH_INFO                                      : /curation_activity_change/34652

  * QUERY_STRING                                   :

  * REMOTE_ADDR                                    : 127.0.0.1

  * REMOTE_PORT                                    : 53346

  * REQUEST_METHOD                                 : POST

  * REQUEST_URI                                    : /stash/curation_activity_change/34652

  * ROUTES_47347061211260_SCRIPT_NAME              : /stash

  * ROUTES_47347096659180_SCRIPT_NAME              :

  * SCRIPT_NAME                                    : /stash

  * SERVER_NAME                                    : localhost

  * SERVER_PORT                                    : 3000

  * SERVER_PROTOCOL                                : HTTP/1.1

  * SERVER_SOFTWARE                                : nginx/1.15.8 Phusion_Passenger/6.0.2

  * action_controller.instance                     : #<StashEngine::AdminDatasetsController:0x00007f69ee568150>

  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x0000561fb020dea8>

  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x00007f69ee552aa8>

  * action_dispatch.cookies_digest                 :

  * action_dispatch.cookies_serializer             : json

  * action_dispatch.encrypted_cookie_salt          : encrypted cookie

  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie

  * action_dispatch.http_auth_salt                 : http authentication

  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x0000561fb25ece28>

  * action_dispatch.logger                         : #<ActiveSupport::Logger:0x0000561fb5ac4038>

  * action_dispatch.parameter_filter               : [:password, /^((?-mix:client_secret|code|authentication_token|access_token|refresh_token))$/]

  * action_dispatch.redirect_filter                : []

  * action_dispatch.remote_ip                      : 104.10.133.166

  * action_dispatch.request.accepts                : [#<Mime::Type:0x0000561fb1983a10 @synonyms=["application/javascript", "application/x-javascript"], @symbol=:js, @string="text/javascript", @hash=-3363854232415186383>, #<Mime::Type:0x00007f69ee55d570 @synonyms=[], @symbol=nil, @string="application/ecmascript", @hash=-2912872302634099661>, #<Mime::Ty...

  * action_dispatch.request.content_type           : application/x-www-form-urlencoded

  * action_dispatch.request.formats                : [#<Mime::Type:0x0000561fb1983a10 @synonyms=["application/javascript", "application/x-javascript"], @symbol=:js, @string="text/javascript", @hash=-3363854232415186383>, #<Mime::Type:0x00007f69ee55d570 @synonyms=[], @symbol=nil, @string="application/ecmascript", @hash=-2912872302634099661>, #<Mime::Ty...

  * action_dispatch.request.parameters             : {"utf8"=>"✓", "resource"=>{"curation_activity"=>{"status"=>"published", "note"=>""}, "publication_date"=>""}, "commit"=>"Submit", "controller"=>"stash_engine/admin_datasets", "action"=>"curation_activity_change", "id"=>"34652"}

  * action_dispatch.request.path_parameters        : {:controller=>"stash_engine/admin_datasets", :action=>"curation_activity_change", :id=>"34652"}

  * action_dispatch.request.query_parameters       : {}

  * action_dispatch.request.request_parameters     : {"utf8"=>"✓", "resource"=>{"curation_activity"=>{"status"=>"published", "note"=>""}, "publication_date"=>""}, "commit"=>"Submit"}

  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"eac0b9c71c5d3eba26c93aaa7d6c0080", "_csrf_token"=>"dSG/AaWemUstYGDaYd/KsEkrrNHsqjjczTuljuD6OWs=", "search"=>{"id"=>nil}, "user_id"=>45960, "show_migrate"=>true, "return_to_path"=>"https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=r9162p5&commit=Search&utf8=%E2%9C%93"}

  * action_dispatch.request_id                     : 8cb8ab72-1791-4e43-abac-106e5339bd01

  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x0000561fb18780f8>

  * action_dispatch.secret_key_base                : a920845587556ebc6d3ca4ba76dd6098c0c96d9cd3043f1289112a3d9086f59466ac06702221927a343f4b396e660bd6a6f3dfa4d512ab7fd555e810702042d2

  * action_dispatch.secret_token                   :

  * action_dispatch.show_detailed_exceptions       : false

  * action_dispatch.show_exceptions                : true

  * action_dispatch.signed_cookie_salt             : signed cookie

  * rack.errors                                    : #<IO:0x0000561faeaa1878>

  * rack.hijack                                    : #<Proc:0x00007f69ee58b7e0@/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:84 (lambda)>

  * rack.hijack?                                   : true

  * rack.input                                     : #<PhusionPassenger::Utils::TeeInput:0x00007f69ee58ba88>

  * rack.multiprocess                              : true

  * rack.multithread                               : false

  * rack.request.cookie_hash                       : {"__utmz"=>"260151704.1564159617.234.2.utmcsr=daringfireball.net|utmccn=(referral)|utmcmd=referral|utmcct=/projects/markdown/dingus", "uvts"=>"b4e3d4cd-9741-4839-75c8-9c4798d6ea65", "__utma"=>"260151704.861099230.1558013536.1568742588.1568747494.389", "_ga"=>"GA1.2.861099230.1558013536", "_gid"=>"GA...

  * rack.request.cookie_string                     : __utmz=260151704.1564159617.234.2.utmcsr=daringfireball.net|utmccn=(referral)|utmcmd=referral|utmcct=/projects/markdown/dingus; uvts=b4e3d4cd-9741-4839-75c8-9c4798d6ea65; __utma=260151704.861099230.1558013536.1568742588.1568747494.389; _ga=GA1.2.861099230.1558013536; _gid=GA1.2.1724426143.1568751185; _gat=1; AWSALB=O45w9UaT+k8L9NJLmyRq5VQisVRK1cnOmR6MWlnqgVDnZ8MmMLaifVmazd02h4rQUAEeikAds4a/Zg1gMwMZ1PWLASH+8dTZToYfKT2+K/WdO/y7YXAWQ3I6DeoJ; _dash2_session=N0V1VmxuSkRuRjZCUE5RbkwzcFBsbGtHY2JXVUg0RDQ5Szc1cGtraVYzWkpzTkRHaTNzMVN0V1FrVkRPS1FvUXhIVjBXSENPUjZBSE1qVE9kZ0dPR09zQ1ZZbmFpZjR5MlhsRTJZdE5zbVQ4VmNmRkdtWTZ6a1RrazY1dmU1ZFpROEw2MmVmUGd2bkdvcko5NWs3NlAzTHhBeHgwZUNRcm03UWlEQjFtaFUrcElqTk9WQmR4OVg5YWVGU043VjB5Q1RwVUU2cTl3ZHhGY0poWit4cXR5ZVd5cUxXQUs2QjdVRXF1Zk9aTGlHRHpBKzZyVHVJWko0djZyQnUyNjE1aTlDZVJhYXFLcHB4eHlTM3NKek96NEdIaE5Jd2JDUHRLRGdDMVRqbUhGUVZNZU5HT3F5Q3pteTlUc0swV01hT0lmT3hONU1zVGZrSkxEeFNQVVkyYXBzRnJoL2o2SXRIcndwekJaT2J3OGRtV1pqMDg2WGRtS1FCUHE3QzRzWXRZVVVESEZrR09zdjNIaUFnd1Y2d3dIdz09LS1oL2Jma2tZWWhKY2tVVzcrZnA0dEZBPT0%3D--18c9b34fa219d1a9fb7bf67e047f2752ea68bf08

  * rack.request.form_hash                         : {"utf8"=>"✓", "resource"=>{"curation_activity"=>{"status"=>"published", "note"=>""}, "publication_date"=>""}, "commit"=>"Submit"}

  * rack.request.form_input                        : #<PhusionPassenger::Utils::TeeInput:0x00007f69ee58ba88>

  * rack.request.form_vars                         : [FILTERED]

  * rack.request.query_hash                        : {}

  * rack.request.query_string                      :

  * rack.run_once                                  : false

  * rack.session                                   : #<ActionDispatch::Request::Session:0x00007f69ee57f080>

  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x00007f69ee57f030>

  * rack.url_scheme                                : http

  * rack.version                                   : [1, 2]

  * warden                                         : Warden::Proxy:70046473516720 @config={:default_scope=>nil, :scope_defaults=>{}, :default_strategies=>{}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x0000561fb28117d0>}



-------------------------------

Backtrace:

-------------------------------



  /apps/dryad/apps/ui/releases/stash/stash_engine/app/models/stash_engine/curation_activity.rb:169:in `block in email_orcid_invitations'

  /apps/dryad/apps/ui/releases/stash/stash_engine/app/models/stash_engine/curation_activity.rb:159:in `each'

  /apps/dryad/apps/ui/releases/stash/stash_engine/app/models/stash_engine/curation_activity.rb:159:in `email_orcid_invitations'

  /apps/dryad/apps/ui/releases/stash/stash_engine/app/models/stash_engine/curation_activity.rb:133:in `submit_to_datacite'

  /apps/dryad/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb:85:in `block (2 levels) in curation_activity_change'

  /apps/dryad/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb:74:in `curation_activity_change'
```

**Comment by ryscher** [comment]
Fixed long long ago!
