### ISSUE TITLE
Publication Update, strange characters, do we need to handle?

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#522]
Seems we're getting all kinds of crap from publications.  We may need further handling code if things like this (a DOI with an @ sign in it) are valid.  Or else we need code to just ignore stupid crap.

```
An URI::InvalidURIError occurred in publications#update:



  bad URI(is not URI?): works/doi: 10.3897/phytokeys.@.38216

  /apps/dryad/local/lib/ruby/2.4.0/uri/rfc3986_parser.rb:67:in `split'





-------------------------------

Request:

-------------------------------



  * URL        : https://datadryad.org/stash_datacite/publications/update

  * HTTP Method: PATCH

  * IP address : 133.82.250.241

  * Parameters : {"utf8"=>"✓", "_method"=>"patch", "authenticity_token"=>"mWtMfRbpzvgch9BKdK6nvLY/RRAKb1t4XXaRwcMPBtMIRrPpNHYlMp0Au5tpB4wh6AHR2E3LuDLlcmfkdCYjTA==", "import_type"=>"published", "internal_datum"=>{"publication"=>"PhytoKeys", "identifier_id"=>"34690", "resource_id"=>"36711", "publication_issn"=>"", "publication_name"=>"", "do_import"=>"true", "msid"=>"#38216", "doi"=>"doi: 10.3897/phytokeys.@.38216"}, "controller"=>"stash_datacite/publications", "action"=>"update"}

  * Timestamp  : 2019-09-26 06:28:40 UTC

  * Server : uc3-dryaduix2-prd-2c

 /apps/dryad/local/lib/ruby/2.4.0/uri/rfc3986_parser.rb:67:in `split'

  /apps/dryad/local/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'

  /apps/dryad/local/lib/ruby/2.4.0/uri/common.rb:231:in `parse'

  /apps/dryad/local/lib/ruby/2.4.0/uri/common.rb:737:in `URI'

  /apps/dryad/apps/ui/releases/stash/stash_datacite/lib/stash/import/crossref.rb:25:in `query_by_doi'

  /apps/dryad/apps/ui/releases/stash/stash_datacite/app/controllers/stash_datacite/publications_controller.rb:67:in `update_doi_metadata'

  /apps/dryad/apps/ui/releases/stash/stash_datacite/app/controllers/stash_datacite/publications_controller.rb:21:in `block (2 levels) in update'

  /apps/dryad/apps/ui/releases/stash/stash_datacite/app/controllers/stash_datacite/publications_controller.rb:15:in `update'
```

**Comment by ryscher** [comment]
Fixed long ago.
