### ISSUE TITLE
Something calling Dryad V1 API not encoding spaces correctly when generating a URI

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#549]
We are getting stack traces like this, which has a URL problem because URLs should use %20 to encode spaces in URL paths and this is not doing that.

```An ActionView::Template::Error occurred in resources#review:

----->  See the error here.

  bad URI(is not URI?): https://v1.datadryad.org/api/v1/journals/Journal of Heredity
  /apps/dryad/local/lib/ruby/2.4.0/uri/rfc3986_parser.rb:67:in `split'


-------------------------------
Request:
-------------------------------

  * URL        : https://datadryad.org/stash_datacite/resources/review.js?id=38011&_=1570658449382
  * HTTP Method: GET
  * IP address : 85.30.28.64
  * Parameters : {"id"=>"38011", "_"=>"1570658449382", "controller"=>"stash_datacite/resources", "action"=>"review", "format"=>"js"}
  * Timestamp  : 2019-10-09 22:00:50 UTC
  * Server : uc3-dryaduix2-prd-2c
  * Rails root : /apps/dryad/apps/ui/releases/20191001202103
  * Process: 11669

-------------------------------
Backtrace:
-------------------------------

  /apps/dryad/local/lib/ruby/2.4.0/uri/rfc3986_parser.rb:67:in `split'
  /apps/dryad/local/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'
  /apps/dryad/local/lib/ruby/2.4.0/uri/common.rb:231:in `parse'
  /apps/dryad/apps/ui/releases/stash/stash_engine/app/models/stash_engine/identifier.rb:218:in `publication_data'
  /apps/dryad/apps/ui/releases/stash/stash_engine/app/models/stash_engine/identifier.rb:244:in `allow_review?'
  /apps/dryad/apps/ui/releases/stash/stash_datacite/app/views/stash_datacite/resources/_review.html.erb:63:in `__apps_dryad_apps_ui_releases_stash_stash_datacite_app_views_stash_datacite_resources__review_html_erb___4111818080163440171_70143909816420'
  /apps/dryad/apps/ui/releases/stash/stash_datacite/app/views/stash_datacite/resources/review.js.erb:3:in `__apps_dryad_apps_ui_releases_stash_stash_datacite_app_views_stash_datacite_resources_review_js_erb__1614369378745309768_70143909873980'
  /apps/dryad/local/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
```

**Comment by ryscher** [comment]
The v1 API is no longer in use.
