### ISSUE TITLE
Cannot duplicate a new version because of invalid authors

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#567]
We should turn off validations while creating a new version.  This is an error we got.

```
An ActiveRecord::RecordInvalid occurred in metadata_entry_pages#new_version:
  Validation failed: Authors is invalid
  /apps/dryad/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/metadata_entry_pages_controller.rb:60:in `duplicate_resource'

-------------------------------
Request:
-------------------------------

  * URL        : https://datadryad.org/stash/metadata_entry_pages/new_version
  * HTTP Method: POST
  * IP address : 107.15.251.14
  * Parameters : {"utf8"=>"✓", "authenticity_token"=>"", "resource_id"=>"37911", "controller"=>"stash_engine/metadata_entry_pages", "action"=>"new_version"}
  * Timestamp  : 2019-10-25 16:35:32 UTC
  * Server : uc3-dryaduix2-prd-2a
    * Rails root : /apps/dryad/apps/ui/releases/20191023170349
  * Process: 23107
-------------------------------
Session:
-------------------------------
  * session id: [FILTERED]
  * data: {"session_id"=>"",
   "_csrf_token"=>"=",
   "user_id"=>6947,
   "show_migrate"=>false,
   "search"=>{"id"=>nil},
   "return_to_path"=>
    "https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=6hdr7sqw4&commit=Search&utf8=%E2%9C%93",
   "saved_email"=>"ehull@datadryad.org"}

-------------------------------
Environment:
-------------------------------

  * CONTENT_LENGTH                                 : 148
    * CONTENT_TYPE                                   : application/x-www-form-urlencoded
    * HTTP_ACCEPT                                    : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
    * HTTP_ACCEPT_ENCODING                           : gzip, deflate, br
    * HTTP_ACCEPT_LANGUAGE                           : en-US,en;q=0.9
    * HTTP_CACHE_CONTROL                             : max-age=0
    * HTTP_COOKIE                                    : __utmz=260151704.1568038845.12.2.utmcsr=t.co|utmccn=(referral)|utmcmd=referral|utmcct=/8v8nrhRfnh; uvts=0967575a-7448-4ff9-62ef-3c63ec718d29; __utma=260151704.1736465687.1567619751.1568742229.1568748259.44; _ga=GA1.2.1736465687.1567619751; tk_tc=YppyjlXyK5wxhNMz; _gid=GA1.2.333804723.1571657254; AWSALB=PFW702vW/dV8fXtapC+pv/9CPkxVwh8WhPMgZ2ZtTDubf1BixsKt+W0zNbpPW2klWIS2ljW1akLFKEkSM8hM2Uw0EsFaIozprmF0UPUHxlzwyE8wnZ0iUtwO9RxG; _dash2_session=blhvSlA2R0hTRWI5RWdsZE1YZFJBSldhN2Z1TEg5c1l2VTB0OXJPYnRGSU9CNXpzUDNDUjgyZUJiWVVIREpsam5jVUlOTSt0QWx6SzBrc2RQaVI1YVRsK0xqc1ZpUnNnbVh4bXgybStIM0tKRVEwQjk4MENzSEs4TzJsbzlLWktTQVpFZDhUT29mSW1HelM2am9pSWNOUWN3c1E4VU5oMElDakhKRE0vdlNoa0hxemxSQStNRUpmUGhBU3BNN1lJUlFJdlZHc05ha2p1SDB0dDVBdUN6ZldsSHI0ZG5XMURhWDRHUGVrUGViWTQ2UTJQbmlGd3p3K3puSFFlSmFQSUU5VTMrRUh4elFkU1NqTjE2R2E1R3Q4MEFwdnFxQWx4eDZjcGs3NE45ekFyUnZYNDI4U2dQY1NUWEdBcTFXMXBHR1lDWFVGcTdZcmxGWUtJS3BYUHlNVnpQMkRvbVlzZmtNeHRvVS9YOG12SmkyVmR0U0NMcHFLbzE0RmZGQTlMY2xCTEsyR294WVo1SnBJMkN4R25EK1RISUg1T3BmTnd3SjJnclJUbnlPemNmN3UwcnluMzIybS9vbDRPdFczOC0tbE5ickxaMTVpNFZBSVlGRjBDRXFyUT09--8ae16b9829a4e2977436e376cafa8082a8696c7d
    * HTTP_HOST                                      : localhost:3000
    * HTTP_ORIGIN                                    : https://datadryad.org
    * HTTP_REFERER                                   : https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=6hdr7sqw4&commit=Search&utf8=%E2%9C%93
    * HTTP_SEC_FETCH_MODE                            : navigate
    * HTTP_SEC_FETCH_SITE                            : same-origin
    * HTTP_SEC_FETCH_USER                            : ?1
    * HTTP_UPGRADE_INSECURE_REQUESTS                 : 1
    * HTTP_USER_AGENT                                : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
    * HTTP_VERSION                                   : HTTP/1.1
    * HTTP_X_AMZN_TRACE_ID                           : Root=1-5db32454-2fc15afccc706758dd885ac0
    * HTTP_X_FORWARDED_FOR                           : 107.15.251.14
    * HTTP_X_FORWARDED_HOST                          : datadryad.org
    * HTTP_X_FORWARDED_PORT                          : 443
    * HTTP_X_FORWARDED_PROTO                         : https
    * HTTP_X_FORWARDED_SERVER                        : datadryad.org
    * ORIGINAL_FULLPATH                              : /stash/metadata_entry_pages/new_version
    * ORIGINAL_SCRIPT_NAME                           :
    * PASSENGER_CONNECT_PASSWORD                     : [FILTERED]
    * PATH_INFO                                      : /metadata_entry_pages/new_version
    * QUERY_STRING                                   :
    * REMOTE_ADDR                                    : 127.0.0.1
    * REMOTE_PORT                                    : 36502
    * REQUEST_METHOD                                 : POST
    * REQUEST_URI                                    : /stash/metadata_entry_pages/new_version
    * ROUTES_47287496884920_SCRIPT_NAME              : /stash
    * ROUTES_47287525825700_SCRIPT_NAME              :
    * SCRIPT_NAME                                    : /stash
    * SERVER_NAME                                    : localhost
    * SERVER_PORT                                    : 3000
    * SERVER_PROTOCOL                                : HTTP/1.1
    * SERVER_SOFTWARE                                : nginx/1.17.3 Phusion_Passenger/6.0.4
    * action_controller.instance                     : #<StashEngine::MetadataEntryPagesController:0x00007f7fe2cbf2f0>
    * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x00005603f3869960>
    * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x00007f7fe2cbbee8>
    * action_dispatch.cookies_digest                 :
    * action_dispatch.cookies_serializer             : json
    * action_dispatch.encrypted_cookie_salt          : encrypted cookie
    * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
    * action_dispatch.http_auth_salt                 : http authentication
    * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x00005603f8138bc8>
    * action_dispatch.logger                         : #<ActiveSupport::Logger:0x00005603f849b540>
    * action_dispatch.parameter_filter               : [:password, /^((?-mix:client_secret|code|authentication_token|access_token|refresh_token))$/]
    * action_dispatch.redirect_filter                : []
    * action_dispatch.remote_ip                      : 107.15.251.14
    * action_dispatch.request.content_type           : application/x-www-form-urlencoded
    * action_dispatch.request.formats                : [#<Mime::Type:0x00005603f4fb9020 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=-3831320286483377910>]
    * action_dispatch.request.parameters             : {"utf8"=>"✓", "authenticity_token"=>"", "resource_id"=>"37911", "controller"=>"stash_engine/metadata_entry_pages", "action"=>"new_version"}
    * action_dispatch.request.path_parameters        : {:controller=>"stash_engine/metadata_entry_pages", :action=>"new_version"}
    * action_dispatch.request.query_parameters       : {}
    * action_dispatch.request.request_parameters     : {"utf8"=>"✓", "authenticity_token"=>"", "resource_id"=>"37911"}
    * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"", "_csrf_token"=>"", "user_id"=>6947, "show_migrate"=>false, "search"=>{"id"=>nil}, "return_to_path"=>"https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=bcc2fqz7h&commit=Search&utf8=%E2%9C%93", "saved_em...
    * action_dispatch.request_id                     : f4ea36b2-c29b-424d-9985-e1ae794205a9
    * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x00005603f4e88570>
    * action_dispatch.secret_key_base                : a920845587556ebc6d3ca4ba76dd6098c0c96d9cd3043f1289112a3d9086f59466ac06702221927a343f4b396e660bd6a6f3dfa4d512ab7fd555e810702042d2
    * action_dispatch.secret_token                   :
    * action_dispatch.show_detailed_exceptions       : false
    * action_dispatch.show_exceptions                : true
    * action_dispatch.signed_cookie_salt             : signed cookie
    * rack.errors                                    : #<IO:0x00005603f1f65860>
    * rack.hijack                                    : #<Proc:0x00007f7fe2cd2828@/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/passenger-6.0.4/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:84 (lambda)>
    * rack.hijack?                                   : true
    * rack.input                                     : #<PhusionPassenger::Utils::TeeInput:0x00007f7fe2cd2a30>
    * rack.multiprocess                              : true
    * rack.multithread                               : false
    * rack.request.form_hash                         : {"utf8"=>"✓",  "resource_id"=>"37911"}
    * rack.request.form_input                        : #<PhusionPassenger::Utils::TeeInput:0x00007f7fe2cd2a30>
    * rack.request.form_vars                         : [FILTERED]
    * rack.request.query_hash                        : {}
    * rack.request.query_string                      :
    * rack.run_once                                  : false
    * rack.session                                   : #<ActionDispatch::Request::Session:0x00007f7fe2cd0118>
    * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x00007f7fe2cd00c8>
    * rack.url_scheme                                : http
    * rack.version                                   : [1, 2]
    * warden                                         : Warden::Proxy:70093621329780 @config={:default_scope=>nil, :scope_defaults=>{}, :default_strategies=>{}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x00005603f8322678>}

-------------------------------
Backtrace:
-------------------------------  /apps/dryad/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/metadata_entry_pages_controller.rb:60:in `duplicate_resource'  /apps/dryad/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/metadata_entry_pages_controller.rb:25:in `new_version'
```

**Comment by ryscher** [comment]
Fixed long ago
