### ISSUE TITLE
Error ingesting in Merritt Sword  Maybe they can tell us why.

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#646]
resource_id: 53937  on 2a
identifier_id: 42535  -- 10.5061/dryad.j6c3v

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<sword:error href="ingest fails:<?xml version="1.0" encoding="UTF-8"?>
<job:jobState xmlns:job='http://uc3.cdlib.org/ontology/mrt/ingest/job'>
    <job:submissionDate>2020-02-18T09:59:17-08:00</job:submissionDate>
    <job:jobStatus>FAILED</job:jobStatus>
    <job:jobStatusMessage>[error] HandlerTransfer: storage service: http://storage.cdlib.org:35121/update/3041/ark%3A%2F13030%2Fm5n63nxf</job:jobStatusMessage>
    <job:localID>doi:10.5061/dryad.j6c3v</job:localID>
    <job:objectCreator>Kicielińska, Jagoda; Szczygieł, Agnieszka; Rossowska, Joanna; Anger, Natalia; Kempińska, Katarzyna; Świtalska, Marta; Kaszowska, Marta; Wietrzyk, Joanna; Boratyński, Janusz; Pajtasz-Piasecka, Elżbieta</job:objectCreator>
    <job:objectTitle>Data from: Oral administration of Polymyxin B modulates the activity of&#10;      Lipooligosaccharide E. coli B against lung metastases in murine tumor&#10;      models</job:objectTitle>
    <job:objectDate>2020</job:objectDate>
    <job:persistentURL>http://n2t.net/ark:/13030/m5n63nxf</job:persistentURL>
    <job:jobID>jid-03f7b0b0-3aac-4f96-bbd2-4bb51cef3e9a</job:jobID>
    <job:primaryID>ark:/13030/m5n63nxf</job:primaryID>
    <job:retainTargetURL>true</job:retainTargetURL>
    <job:packageName>download.183170370292316028.txt</job:packageName>
</job:jobState>" xmlns:sword="http://purl.org/net/sword/terms/"><atom:title xmlns:atom="http://www.w3.org/2005/Atom">ERROR</atom:title><atom:updated xmlns:atom="http://www.w3.org/2005/Atom">2020-02-18T09:59:36Z</atom:updated><atom:generator uri="http://www.swordapp.org/" version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"/><sword:treatment>Processing failed</sword:treatment><atom:summary xmlns:atom="http://www.w3.org/2005/Atom">ingest fails:<?xml version="1.0" encoding="UTF-8"?>
<job:jobState xmlns:job='http://uc3.cdlib.org/ontology/mrt/ingest/job'>
    <job:submissionDate>2020-02-18T09:59:17-08:00</job:submissionDate>
    <job:jobStatus>FAILED</job:jobStatus>
    <job:jobStatusMessage>[error] HandlerTransfer: storage service: http://storage.cdlib.org:35121/update/3041/ark%3A%2F13030%2Fm5n63nxf</job:jobStatusMessage>
    <job:localID>doi:10.5061/dryad.j6c3v</job:localID>
    <job:objectCreator>Kicielińska, Jagoda; Szczygieł, Agnieszka; Rossowska, Joanna; Anger, Natalia; Kempińska, Katarzyna; Świtalska, Marta; Kaszowska, Marta; Wietrzyk, Joanna; Boratyński, Janusz; Pajtasz-Piasecka, Elżbieta</job:objectCreator>
    <job:objectTitle>Data from: Oral administration of Polymyxin B modulates the activity of&#10;      Lipooligosaccharide E. coli B against lung metastases in murine tumor&#10;      models</job:objectTitle>
    <job:objectDate>2020</job:objectDate>
    <job:persistentURL>http://n2t.net/ark:/13030/m5n63nxf</job:persistentURL>
    <job:jobID>jid-03f7b0b0-3aac-4f96-bbd2-4bb51cef3e9a</job:jobID>
    <job:primaryID>ark:/13030/m5n63nxf</job:primaryID>
    <job:retainTargetURL>true</job:retainTargetURL>
    <job:packageName>download.183170370292316028.txt</job:packageName>
</job:jobState></atom:summary><sword:verboseDescription>org.swordapp.server.SwordError: ingest fails:<?xml version="1.0" encoding="UTF-8"?>
<job:jobState xmlns:job='http://uc3.cdlib.org/ontology/mrt/ingest/job'>
    <job:submissionDate>2020-02-18T09:59:17-08:00</job:submissionDate>
    <job:jobStatus>FAILED</job:jobStatus>
    <job:jobStatusMessage>[error] HandlerTransfer: storage service: http://storage.cdlib.org:35121/update/3041/ark%3A%2F13030%2Fm5n63nxf</job:jobStatusMessage>
    <job:localID>doi:10.5061/dryad.j6c3v</job:localID>
    <job:objectCreator>Kicielińska, Jagoda; Szczygieł, Agnieszka; Rossowska, Joanna; Anger, Natalia; Kempińska, Katarzyna; Świtalska, Marta; Kaszowska, Marta; Wietrzyk, Joanna; Boratyński, Janusz; Pajtasz-Piasecka, Elżbieta</job:objectCreator>
    <job:objectTitle>Data from: Oral administration of Polymyxin B modulates the activity of&#10;      Lipooligosaccharide E. coli B against lung metastases in murine tumor&#10;      models</job:objectTitle>
    <job:objectDate>2020</job:objectDate>
    <job:persistentURL>http://n2t.net/ark:/13030/m5n63nxf</job:persistentURL>
    <job:jobID>jid-03f7b0b0-3aac-4f96-bbd2-4bb51cef3e9a</job:jobID>
    <job:primaryID>ark:/13030/m5n63nxf</job:primaryID>
    <job:retainTargetURL>true</job:retainTargetURL>
    <job:packageName>download.183170370292316028.txt</job:packageName>
</job:jobState>
        at org.swordapp.server.CollectionDepositManagerImpl.createNew(CollectionDepositManagerImpl.java:86)
        at org.swordapp.server.CollectionAPI.post(CollectionAPI.java:165)
        at org.swordapp.server.servlets.CollectionServletDefault.doPost(CollectionServletDefault.java:48)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1527)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1484)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
</sword:verboseDescription></sword:error>
```

**Comment by ryscher** [comment]
This dataset is one that failed on initial migration, and I tried to reprocess it.

**Comment by ryscher** [comment]
This dataset was fixed long ago.
