### ISSUE TITLE
Co-author ORCID registration fails (new code or new environment?)

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#81]
The error I get when attempting to register my co-author orcid on the dev server is:

```
Stash::Merritt::DataciteError in StashEngine::SessionsController#orcid_callback

DataCite failed to update metadata for resource 9

---
      def validate_response(response:, operation:)
        raise DataciteError, "DataCite failed to #{operation} for resource #{resource.id}" unless response.status == 201
      end

    end
---

/apps/dryad/apps/ui/releases/stash/stash-merritt/lib/stash/merritt/datacite_gen.rb:44:in `validate_response'
/apps/dryad/apps/ui/releases/stash/stash-merritt/lib/stash/merritt/datacite_gen.rb:22:in `update_metadata'
/apps/dryad/apps/ui/releases/stash/stash-merritt/lib/stash/merritt/submission_job.rb:98:in `update_metadata'
/apps/dryad/apps/ui/releases/stash/stash-merritt/lib/stash/merritt/submission_job.rb:41:in `update_identifier_metadata!'
/apps/dryad/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/sessions_controller.rb:164:in `update_identifier_metadata'
/apps/dryad/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/sessions_controller.rb:145:in `orcid_invitation'
/apps/dryad/apps/ui/releases/stash/stash_engine/app/controllers/stash_engine/sessions_controller.rb:71:in `orcid_preprocessor'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:504:in `block in call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:504:in `each'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:504:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:81:in `run_callbacks'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/abstract_controller/callbacks.rb:19:in `process_action'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_controller/metal/rescue.rb:29:in `process_action'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:164:in `block in instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:164:in `instrument'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.10/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/abstract_controller/base.rb:137:in `process'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionview-4.2.10/lib/action_view/rendering.rb:30:in `process'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_controller/metal.rb:196:in `dispatch'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_controller/metal.rb:237:in `block in action'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:30:in `each'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:30:in `serve'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:817:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `public_send'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `method_missing'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/mapper.rb:51:in `serve'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:30:in `each'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/journey/router.rb:30:in `serve'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/routing/route_set.rb:817:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:407:in `call_app!'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:361:in `callback_phase'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-oauth2-1.5.0/lib/omniauth/strategies/oauth2.rb:75:in `callback_phase'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:230:in `callback_call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:187:in `call!'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/builder.rb:63:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/etag.rb:24:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/conditionalget.rb:25:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/head.rb:13:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/flash.rb:260:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/session/abstract/id.rb:225:in `context'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/session/abstract/id.rb:220:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.10/lib/active_record/query_cache.rb:36:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:377:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:81:in `run_callbacks'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/reloader.rb:73:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:38:in `call_app'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `block in call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:26:in `tagged'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `tagged'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/methodoverride.rb:22:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/runtime.rb:18:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/lock.rb:17:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/static.rb:120:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/static.rb:120:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/static.rb:120:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/sendfile.rb:113:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/application.rb:165:in `call'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/passenger-5.3.3/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/passenger-5.3.3/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/passenger-5.3.3/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/passenger-5.3.3/src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
/apps/dryad/apps/ui/shared/vendor/bundle/ruby/2.4.0/gems/passenger-5.3.3/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

---

session

_csrf_token: "4hB1RvAN/Zt0fm+2faj8bKvuc2QYXckrEWhZ/bvdyac="
omniauth.state: "3e86f2f2cdadc29f6a28498de50c5c2f953b0ab4644b714e"
search: {"id"=>nil}
session_id: "c011de041e917df5eb56da1d3e594c6f"
show_migrate: true
user_id: 27

---
env dump

HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"
HTTP_ACCEPT_ENCODING: "gzip, deflate, br"
HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.9"
REMOTE_ADDR: "172.31.26.197"
SERVER_NAME: "uc3-dryad-dev.cdlib.org"
SERVER_PROTOCOL: "HTTP/1.1"
```

**Comment by briri** [comment]
where do you assign co-author orcids?
