### ISSUE TITLE
undefined method  `affiliation` for StashEngine::User

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#815]
I get this error when trying to create a new dataset from my machine.  I'd never seen this before.  Maybe related to Rails 5 upgrade?

But it seemed to work on the development machine.  Not sure how important or reproducible it is.

```
Unable to create new resource: NoMethodError: undefined method `affiliation' for #<StashEngine::User:0x00007fea577b5fe0>
Did you mean?  affiliation_id
/Users/sfisher/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activemodel-5.0.7.2/lib/active_model/attribute_methods.rb:433:in `method_missing'
/Users/sfisher/workspace/direct-to-cdl-dryad/dryad-app/stash/stash_engine/app/models/stash_engine/resource.rb:589:in `fill_author_from_user!'
/Users/sfisher/workspace/direct-to-cdl-dryad/dryad-app/stash/stash_engine/app/models/stash_engine/resource.rb:574:in `fill_blank_author!'
/Users/sfisher/workspace/direct-to-cdl-dryad/dryad-app/stash/stash_engine/app/controllers/stash_engine/resources_controller.rb:56:in `create'
/Users/sfisher/workspace/direct-to-cdl-dryad/dryad-app/stash/stash_engine/app/controllers/stash_engine/resources_controller.rb:41:in `new'
```

**Comment by ryscher** [comment]
I've seen this issue quite a bit. It usually indicates that you have edited a file that has some dependency relationship that prevents the Rails server from automatically reloading it correctly. Stopping and re-starting Rails should fix it.

**Comment by sfisher** [comment]
Haven't seen again.  Closing.
